### ISSUE TITLE
共享设备，通过短信，短信里的”【青萍空气】“文字请删掉，在末尾增加”[发自青萍空气 App]“

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#105]
如题。

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 请添加“XXX”向您，把连接放在文字的后面
![image](https://user-images.githubusercontent.com/38175831/47475125-c6400a80-d84c-11e8-9211-25cfb81ab728.png)
@GayoZhao 请产品同学确认

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 请用[] 替代【】

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
