### ISSUE TITLE
设备详情，温湿度解读界面，图标的问题

### ISSUE THREAD

**Issue by beibeixiao666** [ClearGrass/Air-App-Issues#110]
如题：

![15391529054222_ pic_hd](https://user-images.githubusercontent.com/39484901/41461202-8f516f8e-70c1-11e8-92fc-d9518e09ce65.jpg)

请改成以上的样式：切图及 psd 会发给你们

**Comment by MiaomiaoCai** [comment]
iOS V82验证已修复
