### ISSUE TITLE
固件更新的逻辑目前有问题，见详情

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#113]
<img width="300" src="https://user-images.githubusercontent.com/37681560/41755868-fa7c9db6-760b-11e8-8d2d-088d29a96d88.png"/>
在上图中，已经提示了有更新。可现在点击“固件更新”后，却依然是检查更新页面（下图）。这样是不对的，应该是“发现有新版本”的页面。
<img width="300" src="https://user-images.githubusercontent.com/37681560/41755934-46a446da-760c-11e8-8d23-27819fcd6e62.png"/>

**Comment by MiaomiaoCai** [comment]
iOS V1.0.4(82)验证已修复
