### ISSUE TITLE
微信登录时，微信显示的app icon、app名称错误。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#117]
如题。
![img_1445](https://user-images.githubusercontent.com/14070164/41785025-f2c676f6-7673-11e8-9ac2-a7dcb5693785.PNG)

@dubiao 请把吴永超加到这个项目里，谢谢。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/47484090-77569d00-d86d-11e8-976d-0c256d425354.png)
![image](https://user-images.githubusercontent.com/38175831/47484131-90f7e480-d86d-11e8-8baf-1774bdf9d4d2.png)
iOS V82，Android V52 验证已修复
