### ISSUE TITLE
温度单位设置为“摄氏度”或“华氏度”时，具体的显示

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#135]
*  卡片中的温度单位始终显示为“°”
*  卡片详情中的温度单位完整显示，即“℃”或“℉”
*  注：城市详情中，天气预报的温度单位始终显示为“°”

**Comment by MiaomiaoCai** [comment]
iOS V110验证已修复
@Dongwei0516 Android V74，城市详情页，天气预报折叠处缺少“°”
![image](https://user-images.githubusercontent.com/38175831/52997464-8f28e100-345b-11e9-9a68-6733efb429bc.png)

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
