### ISSUE TITLE
固件更新提示“网络错误”，按钮变成了可点击的“正在检查更新”，见详情

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#136]
<img width="300" src="https://user-images.githubusercontent.com/37681560/42742344-9e704984-88ec-11e8-9b1b-6cb68e393807.png"/>
<img width="300" src="https://user-images.githubusercontent.com/37681560/42742410-fba38ef4-88ec-11e8-8d1a-656b54505ba2.png"/>
此时按钮的文字应为“检查更新”。

**Comment by MiaomiaoCai** [comment]
V111验证已修复
