### ISSUE TITLE
城市详情，天气预报，温度与风级之间的间距过大，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#137]
<img width="300" src="https://user-images.githubusercontent.com/37681560/42864195-319b9766-8a98-11e8-984a-349109911bc5.png"/>

**Comment by angel-developer** [comment]
版本62解决

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/53313830-2bd4fe00-38f6-11e9-95cf-93a4f9c65e27.png)
V111验证已修复
