### ISSUE TITLE
设备卡片客人端，目前没有：来自“张三”，附需求图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#140]
<img width="300" src="https://user-images.githubusercontent.com/37681560/42929948-2bbc01b0-8b6e-11e8-8fdf-8bac9073f315.jpg"/>

**Comment by angel-developer** [comment]
版本68解决

**Comment by MiaomiaoCai** [comment]
iOS 84验证已修复

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/55872065-a1eba680-5bbe-11e9-9325-85d5d1bb64d4.png)
Android v81验证已修复
