### ISSUE TITLE
共享邀请的链接，微信上有限制，不能直接打开app，需要有一个提示用户使用默认浏览器打开的页面。

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#141]
iOS 端提示文字为：请点击右上角 … ，选择“在Safari中打开”；
Android 端提示文字为：请点击右上角 … ，选择“在浏览器中打开”。
注意：示意图也需要区分 iOS 和 Android 端。

参考设计：
<img width="300" src="https://user-images.githubusercontent.com/37681560/42935358-06e3dbca-8b7c-11e8-9132-dbf41a90df4f.jpg"/>

**Comment by dubinbeta** [comment]
需要研究一下是不是完全没有直接调起的方法。小程序是可以调起app的（例如知乎的）。 @GayoZhao

**Comment by GuiYongZhao** [comment]
是的，小程序是可以调起app的。
杜老师，要不这样，由于小程序的定位是“app的全部功能”，那么微信接受共享的流程，全部由微信小程序完成。 （这样就不需要再打开app去接受共享了，直接在小程序中完成）@dubinbeta

**Comment by dubinbeta** [comment]
在小程序ready之前，还是调app。 @GayoZhao 

小程序ready之后，可以在小程序中完成。

**Comment by jiaruirui323** [comment]
Android 104 验证修复
