### ISSUE TITLE
青萍空气的小数点需求

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#152]
*   当读数的小数点后全是 0，直接取整。（比如湿度 48.0%，应为湿度 48%）
*   城市的 PM2.5 读数取整。
*   设备的 PM2.5 读数保留一位小数，当小数点后是 0，直接取整。（比如 PM2.5 20.0，应为 PM2.5 20）
*   当读数为 0 时，无论后边带几位小数，直接显示 0。（比如 PM2.5 0.0，应为 PM2.5 0）

**Comment by angel-developer** [comment]
iOS v1.1.0 (117） 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
