### ISSUE TITLE
请在长按卡片调出城市和设备管理界面时，轻微震动一下（类似下拉刷新时的效果）

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#157]
如题。

**Comment by GuiYongZhao** [comment]
在此界面调整 item 顺序时，也应该轻微震动一下（参考 iOS 系统的世界时钟排序）。

**Comment by MiaomiaoCai** [comment]
iOS V111验证已修复，iPhone 6S以上的设备支持轻微震动

**Comment by Dongwei0516** [comment]
Android v78 修复。

**Comment by MiaomiaoCai** [comment]
Android V81验证，长按卡片进入编辑页面时有震动效果。
下拉刷新没有震动效果
排序时没有震动效果，因Android有排序按钮，按着就可以拖动
