### ISSUE TITLE
和亲友共享设备页面，点击任意一个“共享方式”后，背景应淡出，附视频

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#158]
[点击任意“共享方式”后.mp4.zip](https://github.com/ClearGrass/Air-App-Issues/files/2248560/mp4.zip)

**Comment by GuiYongZhao** [comment]
此时的状态栏应为黑色。
<img width="275" alt="image" src="https://user-images.githubusercontent.com/37681560/43509587-a4cd3cf4-95a5-11e8-8350-0adeab31e1cb.png">

**Comment by MiaomiaoCai** [comment]
97验证已修复
