### ISSUE TITLE
主界面，未连接的Snow和未连接的Goose，显示逻辑应一致——都应有灰色蒙板

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#173]
如题。

![wechatimg199](https://user-images.githubusercontent.com/14070164/44206071-1b93d780-a18b-11e8-89d7-3e4b0e604c89.jpg)

**Comment by MiaomiaoCai** [comment]
iOS 97验证已修复

**Comment by MiaomiaoCai** [comment]
Android V74验证已修复
