### ISSUE TITLE
美国标准，读数和“名词解释页中的读数”不一致，应一致，附视频

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#174]
[赵桂勇 2018-08-08 17.27.19.mp4.zip](https://github.com/ClearGrass/Air-App-Issues/files/2309677/2018-08-08.17.27.19.mp4.zip)

**Comment by angel-developer** [comment]
版本62解决

**Comment by MiaomiaoCai** [comment]
82验证已修复
