### ISSUE TITLE
AQI的名词解释页，触发区域不应是“优”，而应是AQI数据卡片，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#176]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/44571417-57462700-a7b3-11e8-8be5-d3806a353313.png">

**Comment by dubinbeta** [comment]
原来是点“优”啊，点“优”也可以，把点“AQI”加上就行，不需要把点“优”去掉。

**Comment by GuiYongZhao** [comment]
收到。
