### ISSUE TITLE
App中Snow的实时数据与Snow的真实数据有出入

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#178]
*   PM2.5还未加一位小数
*   tVOC的数据相差较大
*   二氧化碳经常相差1
*   温度、相对湿度的数据比较及时

**Comment by GuiYongZhao** [comment]
<img width="300" src="https://user-images.githubusercontent.com/37681560/45143931-39cf7f00-b1ef-11e8-917d-a7bd97701608.png"/>

**Comment by angel-developer** [comment]
iOS 版本 83 解决。

**Comment by MiaomiaoCai** [comment]
iOS V111验证已修复，Android V74验证已修复
