### ISSUE TITLE
选择城市的搜索框“叉号”出现的时机不对

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#18]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/37681560/40487365-8920d4c4-5f96-11e8-8a76-77120d92e86b.png">
应该在搜索框内有文字时，出现叉号。

**Comment by MiaomiaoCai** [comment]
iOS61验证已修复

**Comment by MiaomiaoCai** [comment]
Android V45验证已修复
