### ISSUE TITLE
Goose同步完数据后，每次进设备详情，历史数据柱都会闪动一下，附视频

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#180]
[赵桂勇 2018-08-08 17.24.54.mp4.zip](https://github.com/ClearGrass/Air-App-Issues/files/2317789/2018-08-08.17.24.54.mp4.zip)

**Comment by MiaomiaoCai** [comment]
iOS V111验证未复现

**Comment by jiaruirui323** [comment]
Android 104 验证未复现

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证未复现
