### ISSUE TITLE
设备详情界面，读数历史名称文字旁边的单位文字、选中的读数大字旁边的时间文字，底部被切掉了一部分，不应如此。评论中有图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#190]
如题。
![img_1910](https://user-images.githubusercontent.com/14070164/44701713-a4334180-aac2-11e8-9669-fe8912beaa99.jpg)

**Comment by MiaomiaoCai** [comment]
108验证已修复
![image](https://user-images.githubusercontent.com/38175831/51890495-2c51a600-23d7-11e9-98b5-640d4beca351.png)
