### ISSUE TITLE
英文，添加设备后命名设备的界面，标题文字底部被截断，评论中有图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#192]
如题。
![img_1854](https://user-images.githubusercontent.com/14070164/44707252-8ff93f80-aad6-11e8-8017-68fe796ef5e9.jpg)

**Comment by MiaomiaoCai** [comment]
108验证已修复
![image](https://user-images.githubusercontent.com/38175831/51890847-31fbbb80-23d8-11e9-9ffa-9818e3ed5088.png)
