### ISSUE TITLE
管理设备，检查更新，UI显示问题，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#198]
![img_1928](https://user-images.githubusercontent.com/14070164/44715323-1703e300-aaea-11e8-818e-b2f0fb94fb39.jpg)

**Comment by angel-developer** [comment]
版本62解决

**Comment by MiaomiaoCai** [comment]
V108验证，未显示设备名称，检查更新的圆圈也没有调整

**Comment by angel-developer** [comment]
iOS v125 修复。圆圈已调整， 设备名称暂不添加。

**Comment by MiaomiaoCai** [comment]
126验证已修复
