### ISSUE TITLE
设备管理，提交反馈，界面上的“Send”按钮位置不合理，当虚拟键盘被调起时，手机号和email输入框会被遮挡

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#199]
请把“Send”按钮文字改为“Submit”，并放到右上角。

**Comment by MiaomiaoCai** [comment]
@Dongwei0516，请把Submit按钮放在右上角
![image](https://user-images.githubusercontent.com/38175831/51893742-c1a56800-23e0-11e9-876b-0185d729e726.png)

**Comment by Dongwei0516** [comment]
Android v90 修复。

**Comment by MiaomiaoCai** [comment]
Android V91，请用“提交”、“Submit”替换“发送”、“Send”
![image](https://user-images.githubusercontent.com/38175831/57211512-1b868100-7013-11e9-92c3-b7e14e1e2608.png)

**Comment by dubinbeta** [comment]
”E-mail“请改为”Email“。

**Comment by MiaomiaoCai** [comment]
Android V91，请更新提示语，包括中英文
![image](https://user-images.githubusercontent.com/38175831/57212634-ed0aa500-7016-11e9-86f8-b5e2e77243c1.png)
![image](https://user-images.githubusercontent.com/38175831/57212641-f3991c80-7016-11e9-9c42-4d7498a5512a.png)
![image](https://user-images.githubusercontent.com/38175831/57212870-9a7db880-7017-11e9-8418-7a6861953654.png)

**Comment by Dongwei0516** [comment]
Android v95 更新提示语。

**Comment by MiaomiaoCai** [comment]
Android V102验证已修复
