### ISSUE TITLE
分享或共享，失败，请不要显示失败提示，因为很有可能是用户自己取消的。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#200]
如题。

**Comment by MiaomiaoCai** [comment]
Android V74，验证未修复，取消微信分享后弹出提示
![image](https://user-images.githubusercontent.com/38175831/53799346-279f8500-3f75-11e9-96be-0408f040f44a.png)

**Comment by MiaomiaoCai** [comment]
iOS V117验证无提示

**Comment by MiaomiaoCai** [comment]
Android V77未见提示
