### ISSUE TITLE
分享出来的设备的图片的问题，详见评论中的图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#207]
![img_1939](https://user-images.githubusercontent.com/14070164/44729437-61e52100-ab11-11e8-80f1-d265bcb9fb2f.jpg)

**Comment by MiaomiaoCai** [comment]
iOS90验证已修复
![image](https://user-images.githubusercontent.com/38175831/48936630-71c0a580-ef46-11e8-9a62-53d26d8d684d.png)

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64588662-ab7b7380-d3d5-11e9-9e0f-a1ea3fbdaf2a.png)
