### ISSUE TITLE
设备详情，设备管理，修改设备名称的界面的样式，应和意见反馈界面一样（默认大字显示界面标题，界面可以滚动）。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#211]
如题。

**Comment by MiaomiaoCai** [comment]
@angel-developer 84验证未修复

**Comment by angel-developer** [comment]
iOS v125 修复。

**Comment by MiaomiaoCai** [comment]
iOS V143验证未修复，修改设备名称的页面未实现

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58147379-c42c1600-7c8c-11e9-9045-a17e525a117a.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证未修复
修改设备名称的界面的样式，应和意见反馈界面一样（默认大字显示界面标题）
![image](https://user-images.githubusercontent.com/52393989/64311121-74702100-cfd5-11e9-8fb2-177f5ed93b9d.png)

**Comment by jiaruirui323** [comment]
Android v121验证未修复
意见反馈、修改设备名称的界面的样式，参考ios意见反馈界面一样（默认大字显示界面标题）
![image](https://user-images.githubusercontent.com/52393989/64592500-bedf0c80-d3de-11e9-8125-f85038763cbb.png)
