### ISSUE TITLE
设备详情，设备管理，共享设备，在点击共享按钮后取消，界面顶部的状态栏颜色显示错误（没有恢复为黑色）

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#212]
如题。
![img_1960](https://user-images.githubusercontent.com/14070164/44771640-280e2c00-ab9e-11e8-8a7e-43ab28cdce38.PNG)

**Comment by MiaomiaoCai** [comment]
90验证已修复
