### ISSUE TITLE
主界面，如某卡片设备名称较长，且未连接，则此时应以“...”截断设备名称，保证“未连接”文字被正确显示。此时可不显示上次更新时间。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#216]
<img width="444" alt="screen shot 2018-08-29 at 4 23 59 pm" src="https://user-images.githubusercontent.com/14070164/44775461-411bda80-aba8-11e8-8006-0ca9cea94949.png">

**Comment by angel-developer** [comment]
版本62修改

**Comment by MiaomiaoCai** [comment]
iOS90验证已修复
![image](https://user-images.githubusercontent.com/38175831/48938076-1218c900-ef4b-11e8-83e0-5c39d42bbdb2.png)

**Comment by MiaomiaoCai** [comment]
iOS90验证已修复

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
Android V94验证已修复
