### ISSUE TITLE
主界面，温湿度计的卡片上的蓝牙图标太大了，需要适当改小

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#217]
![img_1967](https://user-images.githubusercontent.com/14070164/44776451-b12b6000-abaa-11e8-989a-08b7b0e42762.jpg)

**Comment by MiaomiaoCai** [comment]
iOS 90验证已修复
Android 56未修复

**Comment by Dongwei0516** [comment]
已更新图标

**Comment by MiaomiaoCai** [comment]
Android v91验证已修复
