### ISSUE TITLE
读数评价颜色，应和Snow的保持一致。目前至少湿度“潮湿”的不一致。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#221]
请 @yezhinan @GayoZhao 对一遍。
![img_1940](https://user-images.githubusercontent.com/14070164/44779201-6c56f780-abb1-11e8-9821-9a9f0fbe7db5.jpg)

**Comment by angel-developer** [comment]
版本62修改

**Comment by MiaomiaoCai** [comment]
117 验证已修复
![image](https://user-images.githubusercontent.com/38175831/53801347-e65da400-3f79-11e9-9c79-ed26dd013d65.png)
