### ISSUE TITLE
二氧化碳的读数解读，简体中文和繁体中文开头的文字需要修改，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#222]
简体原文：二氧化碳是空气中常见的化合物，约占大气体积的 0.04%（400 ppm）
需修改为：CO2 即二氧化碳，是空气中常见的化合物，约占大气体积的 0.04%（400 ppm）

繁体原文：二氧化碳是空氣中常見的化合物，約占大氣體積的 0.04%（400 ppm）。
需修改为：CO2 即二氧化碳，是空氣中常見的化合物，約占大氣體積的 0.04%（400 ppm）。

英文无需修改。

**Comment by dubinbeta** [comment]
#204

**Comment by MiaomiaoCai** [comment]
iOS V110，Android V74验证已修复
