### ISSUE TITLE
接受共享的弹窗，设备名被截断，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#229]
我的设备名字是“青萍空气检测仪”
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/44840082-ee5b2500-ac72-11e8-879d-c00e12915b2e.png">

**Comment by MiaomiaoCai** [comment]
V110验证已修复
![image](https://user-images.githubusercontent.com/38175831/52692971-63f84a80-2fa0-11e9-82e4-64ee6884970a.png)
