### ISSUE TITLE
城市详情，UI修改意见，请看评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#230]
![img_d466a0b7dd02-1](https://user-images.githubusercontent.com/14070164/44842932-ad1a4380-ac79-11e8-9c7e-9a223e59a3d4.jpg)

**Comment by dubinbeta** [comment]
补充：“Yesterday”改为具体日期，“Today”不受影响。

**Comment by MiaomiaoCai** [comment]
61验证已修复
