### ISSUE TITLE
更新固件的界面，文字的问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#231]
![pasted_image_2018_8_31__6_05_pm](https://user-images.githubusercontent.com/14070164/44906828-95f65700-ad48-11e8-8520-6f499665514e.jpg)

**Comment by MiaomiaoCai** [comment]
V110测试服务器，验证已修复
![image](https://user-images.githubusercontent.com/38175831/52693815-c9e5d180-2fa2-11e9-8390-d575e19275f8.png)
