### ISSUE TITLE
目前的通知，都没必要让app带上未读数badge

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#232]
如题。

![wechatimg216](https://user-images.githubusercontent.com/14070164/44906897-d48c1180-ad48-11e8-8f60-c9e058919645.jpeg)

**Comment by dubinbeta** [comment]
问题还在。

**Comment by dubinbeta** [comment]
问题还在！

**Comment by angel-developer** [comment]
iOS 1.1.0 （125） 修复。

**Comment by MiaomiaoCai** [comment]
iOS V143验证已修复
