### ISSUE TITLE
添加城市，候选城市列表，文字过小，需要适当调大

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#234]
如题。

![img_1996](https://user-images.githubusercontent.com/14070164/44918029-96084e00-ad6c-11e8-835e-ea0decc4e911.jpg)

**Comment by MiaomiaoCai** [comment]
iOS V110，Android V74验证已修复
![image](https://user-images.githubusercontent.com/38175831/52695045-6eb5de00-2fa6-11e9-9360-7bc47aab862b.png)
![image](https://user-images.githubusercontent.com/38175831/52695306-20eda580-2fa7-11e9-8748-a8034010cdc8.png)
