### ISSUE TITLE
英文，共享设备的短信，文案修改意见

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#235]
请改为：

"xxx" is sharing "xxxx" with you: https://cleargrass.com/sharing_device/xxxxx [via ClearGrass Air]

xxx = 用户登录名
xxxx = 设备名

**Comment by MiaomiaoCai** [comment]
iOS62验证已修复

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58088710-d3ac5000-7bf5-11e9-9fbf-027057bef938.png)
Android V94验证未修复

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V102验证未修复，官网地址为空
![image](https://user-images.githubusercontent.com/38175831/59403680-37c9ca80-8dd6-11e9-9fad-fca8ed9071bd.png)

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64592070-c5b94f80-d3dd-11e9-8519-04d62f887a7c.png)
