### ISSUE TITLE
读数解读界面，分级的文字评价，过长被截断了，需要缩小文字或增大高度来“装下”它们。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#236]
请 @beibeixiao666 @yezhinan 给出设计。

![img_1998](https://user-images.githubusercontent.com/14070164/44918595-f3e96580-ad6d-11e8-8939-64748ac32c49.PNG)

**Comment by MiaomiaoCai** [comment]
@yezhinan 'Hazardous'字母顶到边框，请调整单词的宽度
![image](https://user-images.githubusercontent.com/38175831/45087088-59a36c00-b137-11e8-8f54-8b41c15e281b.png)

**Comment by MiaomiaoCai** [comment]
@yezhinan 'Moderately'单词不可以换行显示
![image](https://user-images.githubusercontent.com/38175831/45087277-e1897600-b137-11e8-93f8-cd8bcc9e3ab6.png)

**Comment by MiaomiaoCai** [comment]
@angel-developer 'Moderately polluted'和'Slightly polluted'请交换位置
![image](https://user-images.githubusercontent.com/38175831/45087386-3af1a500-b138-11e8-86b0-e37a0b2cd32d.png)
“非常不健康”请显示完整
![image](https://user-images.githubusercontent.com/38175831/45087413-5066cf00-b138-11e8-98c8-c12806621a6e.png)

**Comment by angel-developer** [comment]
iOS  v1.1.0 （125） 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58152044-10cc1d00-7c9e-11e9-838e-cc605dcbf7f7.png)
iOS V143，缺少一个字母'y'

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64310899-aaf96c00-cfd4-11e9-8d18-94c36bce0d23.png)
