### ISSUE TITLE
设备详情，英文，温湿度解读界面的一系列问题，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#239]
![img_2006](https://user-images.githubusercontent.com/14070164/44966490-0f22c380-af6e-11e8-9ad7-c1d2650142e4.jpg)

**Comment by MiaomiaoCai** [comment]
@angel-developer  换行后也需要缩进
![image](https://user-images.githubusercontent.com/38175831/45087565-f581a780-b138-11e8-870c-511052c19738.png)

**Comment by angel-developer** [comment]
iOS  v125 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58157162-5393f200-7caa-11e9-9443-1bcce2f16535.png)
iOS v 143验证已修复
