### ISSUE TITLE
首页下拉刷新时，滚动条超出title栏，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#242]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/44967402-a2aac300-af73-11e8-8c6f-2c4c970e50a3.png">

**Comment by angel-developer** [comment]
iOS v1.1.0 (125) 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56125702-18681a00-5fac-11e9-99bb-21c70cda9383.png)
iOS V141验证已修复
