### ISSUE TITLE
编辑模式，item超过一屏时，最下item无法移至list最上，附视频

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#246]
[item无法移至最上.mp4.zip](https://github.com/ClearGrass/Air-App-Issues/files/2345078/item.mp4.zip)

**Comment by angel-developer** [comment]
iOS v1.1.0 (125) 修复。

**Comment by MiaomiaoCai** [comment]
iOS V141验证，item向下滑动有卡顿，需优化

**Comment by jiaruirui323** [comment]
Android 104 验证没有问题
