### ISSUE TITLE
首页登录微信后，未及时显示登录状态（附图）

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#251]
V61
1.首页-点击登录-微信登录
2.登录成功返回app首页
3.未显示已登录状态，且左上角显示返回微信的按钮
预期结果：无需刷新页面，立即显示已登录，且没有返回微信的按钮
![default](https://user-images.githubusercontent.com/38175831/45075669-7a10fd80-b11a-11e8-8aa3-bcc33bd02f33.jpg)

**Comment by angel-developer** [comment]
版本62解决

**Comment by MiaomiaoCai** [comment]
iOS62验证已修复
