### ISSUE TITLE
添加城市进入详情页后无法直接返回到首页

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#256]
V61
	1.首页-添加城市质量-北京-昌平
	2.城市详情页-侧滑返回
	3.返回城区选择页面
	预期结果：直接回到App首页（页面左上角返回按钮已实现）

**Comment by angel-developer** [comment]
新添加城市进入城市详情后，目前无法侧滑进入首页，暂时禁用这里的侧滑。
