### ISSUE TITLE
设备分享的链接，点击进入显示乱码

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#257]
iOSV61
	1.首页-点击Snow设备卡片-设置
	2.分享设备-微信分享
	3.微信打开分享链接-显示一段代码
	预期结果：显示设备信息及分享方信息
![image](https://user-images.githubusercontent.com/38175831/45133282-f6f9b100-b1c6-11e8-8ed1-4bf7a512189d.png)

**Comment by guoyanjun5** [comment]
已解决。

**Comment by dubinbeta** [comment]
@guoyanjun5 ，不要直接close issue，标记为fixed并回复， @MiaomiaoCai 会来检查，核实后会close。

**Comment by server-go** [comment]
@dubinbeta   好的

**Comment by MiaomiaoCai** [comment]
验证已修复
