### ISSUE TITLE
添加设备，自定义设备名称页面，title文字应是黑色，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#260]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/45151893-21b52b00-b202-11e8-84a2-44ecd0a10ec6.png">

**Comment by angel-developer** [comment]
版本62解决

**Comment by MiaomiaoCai** [comment]
iOS62验证已修复
