### ISSUE TITLE
添加Snow后，出现名称为空

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#261]
1.  首页-添加Snow-输入验证码
2.  添加成功进入“命名设备页”
3.  点击“自定义设备名称”
4.  不输入内容，返回“命名设备页”
5.  点击“跳过”
6.回到首页，设备名称为空

**Comment by angel-developer** [comment]
版本65解决。

**Comment by MiaomiaoCai** [comment]
V69验证已修复
