### ISSUE TITLE
设备详情界面，某项读数的历史数据暂无时，英文目前显示的是“no data”，请改为“No data yet.”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#262]
如题。
![img_2023](https://user-images.githubusercontent.com/14070164/45164019-238fe600-b224-11e8-8cfe-1debc5f78316.jpg)

**Comment by angel-developer** [comment]
版本65解决。

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 @angel-developer 请为提示语加个句点。

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by Dongwei0516** [comment]
Android v65 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
