### ISSUE TITLE
微信授权界面，app名称不应为“青萍空气监测”，应为“青萍空气”。如果可以定义英文名，则应为“ClearGrass Air”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#263]
如题。
![img_2025](https://user-images.githubusercontent.com/14070164/45164207-939e6c00-b224-11e8-873b-1ce2f79744f7.jpg)

**Comment by MiaomiaoCai** [comment]
iOS V84，Android V52验证已修复
