### ISSUE TITLE
城市或设备详情，行动建议区域，内容的左起位置过于靠右，导致左侧的空白区域过大，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#265]
![img_2024](https://user-images.githubusercontent.com/14070164/45164725-b2513280-b225-11e8-9e81-1e88d8396d03.jpg)

**Comment by GuiYongZhao** [comment]
请 @yezhinan @beibeixiao666 提供行动建议的左右空白间距。

**Comment by angel-developer** [comment]
设计已更改，风向错误 iOS v1.1.0 (125) 修复。

**Comment by MiaomiaoCai** [comment]
iOS v 144验证已修复
![image](https://user-images.githubusercontent.com/38175831/58157830-c487d980-7cab-11e9-80f1-c51c70881cc7.png)

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64590827-02d01280-d3db-11e9-9b86-dad651b3e1c5.png)
