### ISSUE TITLE
Snow设备端显示某些日期有历史，但青萍空气app端显示没有。详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#266]
Snow端（0066版，正式服务器）有历史：
![img_2031](https://user-images.githubusercontent.com/14070164/45165257-0577b500-b227-11e8-90fe-e7e3d2a1479c.jpg)

青萍空气app端（0062版，正式服务器）没有历史：
![img_2029](https://user-images.githubusercontent.com/14070164/45165273-132d3a80-b227-11e8-9ceb-58dfa92d05ca.jpg)

青萍空气app是在正式环境，[(title: "PhoneId", index: 11, value: Optional("F53A7CA7-DA00-5735-8093-D226A512CE8F"))]。

**Comment by server-go** [comment]
查了下数据库，APP显示对的，2-6号服务器上没数据。Snow上面显示有问题，我发给任成龙和虎正玺看看。

**Comment by guoyanjun5** [comment]
`{
    "code": 0,
    "data": [
        {
            "_id": {
                "$oid": "5b91502c47632e017c010ff0"
            },
            "type": "pm25",
            "max": 165,
            "min": 0,
            "timestamp": 1536163200,
            "created_at": 1536249900
        },
        {
            "_id": {
                "$oid": "5b8ab8ac47632e303618468a"
            },
            "type": "pm25",
            "max": 40,
            "min": 1,
            "timestamp": 1535731200,
            "created_at": 1535817900
        },
        {
            "_id": {
                "$oid": "5b89672c47632e3ace377c1c"
            },
            "type": "pm25",
            "max": 190,
            "min": 0,
            "timestamp": 1535644800,
            "created_at": 1535731500
        },
        {
            "_id": {
                "$oid": "5b8815ac47632e41542e7b17"
            },
            "type": "pm25",
            "max": 200,
            "min": 0,
            "timestamp": 1535558400,
            "created_at": 1535645100
        },
        {
            "_id": {
                "$oid": "5b86c42c47632e465f32e970"
            },
            "type": "pm25",
            "max": 36,
            "min": 0,
            "timestamp": 1535472000,
            "created_at": 1535558700
        }
    ]
}`
`{
    "code": 0,
    "data": [
        {
            "_id": {
                "$oid": "5b91502c47632e017c010ff4"
            },
            "type": "co2",
            "max": 2211,
            "min": 344,
            "timestamp": 1536163200,
            "created_at": 1536249900
        },
        {
            "_id": {
                "$oid": "5b8ab8ac47632e303618468e"
            },
            "type": "co2",
            "max": 1720,
            "min": 412,
            "timestamp": 1535731200,
            "created_at": 1535817900
        },
        {
            "_id": {
                "$oid": "5b89672c47632e3ace377c20"
            },
            "type": "co2",
            "max": 1888,
            "min": 355,
            "timestamp": 1535644800,
            "created_at": 1535731500
        },
        {
            "_id": {
                "$oid": "5b8815ac47632e41542e7b1b"
            },
            "type": "co2",
            "max": 2589,
            "min": 361,
            "timestamp": 1535558400,
            "created_at": 1535645100
        },
        {
            "_id": {
                "$oid": "5b86c42c47632e465f32e974"
            },
            "type": "co2",
            "max": 1722,
            "min": 344,
            "timestamp": 1535472000,
            "created_at": 1535558700
        }
    ]
}`
这是数据库存在的数据。 @YoungManH
