### ISSUE TITLE
英文，城市名，顺序应该颠倒过来。如“Beijing - Chaoyang”应为“Chaoyang - Beijing”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#268]
如题。

**Comment by angel-developer** [comment]
版本65解决。

**Comment by MiaomiaoCai** [comment]
iOS V69验证已修复

**Comment by MiaomiaoCai** [comment]
Android V74未修复，请改为“Chaoyang, Beijing”，与iOS V108保持一致

**Comment by Dongwei0516** [comment]
Android v92修复。

**Comment by MiaomiaoCai** [comment]
Android V102验证已修复
![image](https://user-images.githubusercontent.com/38175831/59404111-e3bfe580-8dd7-11e9-9527-b358397a5795.png)
