### ISSUE TITLE
升级固件的界面的UI修改意见，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#271]
如题。
<img width="1119" alt="screen shot 2018-09-06 at 11 56 23 pm" src="https://user-images.githubusercontent.com/14070164/45169613-956e2c80-b230-11e8-8416-393b060d9869.png">

**Comment by dubinbeta** [comment]
我看到已经改了，但是“发现新版”文字和更新说明文字框之间的间距过大：
![wechatimg13059](https://user-images.githubusercontent.com/14070164/45336768-82a08280-b5b7-11e8-9aad-24e0c3fc9da2.jpg)

**Comment by angel-developer** [comment]
版本69解决。

**Comment by MiaomiaoCai** [comment]
iOS V110，验证已修复
![image](https://user-images.githubusercontent.com/38175831/53064524-154c3280-3503-11e9-9c7b-cd6922e6542f.png)

**Comment by MiaomiaoCai** [comment]
Android V91，Snow图标为灰色，请使用蓝色，另“立即更新”用“下载”替换，因为更新过程在设备端完成
![image](https://user-images.githubusercontent.com/38175831/57190404-4eb20d00-6f4c-11e9-8b2f-934510b4b64e.png)
