### ISSUE TITLE
英文，设备详情，设备管理，意见反馈界面的字符串错误，“Your feedback”写成了“Yor feedback”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#272]
如题。
![img_2040](https://user-images.githubusercontent.com/14070164/45169780-e4b45d00-b230-11e8-9d61-022f870df605.jpg)

**Comment by angel-developer** [comment]
版本65 解决

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 英文文案请与iOS版统一
![image](https://user-images.githubusercontent.com/38175831/46067559-b5e33400-c1a9-11e8-9102-3265fb459859.png)

**Comment by Dongwei0516** [comment]
Android v65 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
