### ISSUE TITLE
设备详情，设备管理，更新固件，正在更新和更新失败的界面的文字问题，详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#273]
![img_2042](https://user-images.githubusercontent.com/14070164/45170797-568da600-b233-11e8-99f9-4ab6bd690276.jpg)

![img_2041](https://user-images.githubusercontent.com/14070164/45170804-5ab9c380-b233-11e8-8c50-95a82f5a973c.jpg)

**Comment by angel-developer** [comment]
版本65 解决。

**Comment by MiaomiaoCai** [comment]
iOS V110 验证已修复
![image](https://user-images.githubusercontent.com/38175831/52854941-09571e00-315b-11e9-8cc7-57ebb70da460.png)

**Comment by Dongwei0516** [comment]
Android v120 修复。
