### ISSUE TITLE
Snow客人端的设备管理页，应去掉共享设备的描述，见图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#276]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/45198011-be290d00-b296-11e8-94bf-c888da9cd87f.png">

**Comment by dubinbeta** [comment]
另外，From“赵桂勇”应该在引号前面加个空格，即变成：From “赵桂勇”

**Comment by angel-developer** [comment]
版本65解决

**Comment by MiaomiaoCai** [comment]
V69验证已修复
