### ISSUE TITLE
温湿度解读界面的文字和元素间距问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#277]
![img_9fc95c1b1080-1](https://user-images.githubusercontent.com/14070164/45199489-89b94f00-b29e-11e8-9ac3-81306ef1e4cd.jpg)

**Comment by angel-developer** [comment]
版本68解决。

**Comment by MiaomiaoCai** [comment]
@angel-developer iOS V110 验证，第三处未优化
![image](https://user-images.githubusercontent.com/38175831/52852145-c4c78480-3152-11e9-96cb-5a238b4e65de.png)

**Comment by angel-developer** [comment]
iOS v126 修复。iPhone 6s 以上大屏幕 缩小一个字体， 小屏幕（iPhone 5）缩小两个字体。
<img width="306" alt="屏幕快照 2019-03-19 上午11 51 50" src="https://user-images.githubusercontent.com/20908900/54579375-258df980-4a3e-11e9-8dd5-035c9ef759e8.png">

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54737723-3d0ae500-4bec-11e9-9f16-0999a24ffcff.png)
@angel-developer iOS V126，“26.5”和“Temp”之间的间距需要增加

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64247415-696bb100-cf41-11e9-9a37-371df87aa6a3.png)
