### ISSUE TITLE
Goose的未连接说明界面的文字问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#279]
![img_2050](https://user-images.githubusercontent.com/14070164/45260570-a3cd6b80-b41d-11e8-8cf1-d087da5d99c4.jpg)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64328871-d1cd9780-d000-11e9-824b-6295ad624db2.png)
