### ISSUE TITLE
英文，添加Goose之后，自定义名称，名称输入框内的文字问题，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#280]
1. 默认填入的文字，目前是“ClearGrass Temperature and Humidity Mon”被截断了，我试了一下，写全是39个字符，应该写全。如果担心框里放不下，可以改用“Temperature and Humidity Monitor”。
<img width="438" alt="screen shot 2018-09-12 at 2 52 16 pm" src="https://user-images.githubusercontent.com/14070164/45407262-75f55a80-b69b-11e8-90c5-7ac67e18cf32.png">

2. 删去填入的文字后，占位提示文字，目前是“Air Monitor”，可改为“Temperature and Humidity Monitor”。
<img width="435" alt="screen shot 2018-09-12 at 2 52 46 pm" src="https://user-images.githubusercontent.com/14070164/45407283-8c031b00-b69b-11e8-96f6-ec9cf9b49cb7.png">

**Comment by GayoZhao** [comment]
这里不应该有默认填入的文字，“Temperature and Humidity Monitor”应是占位提示文字，当用户什么都不输入，直接点击Done后，设备名应为“Temperature and Humidity Monitor”。

**Comment by angel-developer** [comment]
版本68解决。

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by MiaomiaoCai** [comment]
Android V102验证未修复，请参考iOS
![image](https://user-images.githubusercontent.com/38175831/59426817-b8ef8480-8e0b-11e9-8d52-1dcfb7cb6528.png)
![image](https://user-images.githubusercontent.com/38175831/59426844-c86ecd80-8e0b-11e9-86cc-834292190f7a.png)

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64588501-2abc7780-d3d5-11e9-9427-5c67d1f2d11f.png)
