### ISSUE TITLE
App已获得定位权限，添加城市，定位城市的文字应为定位城市名（比如“朝阳”），目前依然是“定位城市”，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#281]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/45540434-06b86b80-b83f-11e8-8cf9-83b56464148d.png">

**Comment by angel-developer** [comment]
iOS 版本83 解决。

**Comment by MiaomiaoCai** [comment]
110验证，进入添加城市页，此处会闪现“定位城市”或“未知”字符，而后显示当前城市名

**Comment by jiaruirui323** [comment]
Android 104 验证，进入添加城市页，此处会闪现“定位城市”字符，而后显示当前城市名
