### ISSUE TITLE
[偶发]设备详情，侧滑返回取消后，标题栏变白，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#285]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/45610514-bdf6f180-ba8e-11e8-9700-b8959e4caacc.png">

**Comment by angel-developer** [comment]
iOS 版本83解决。

**Comment by MiaomiaoCai** [comment]
108验证未复现，会继续观察

**Comment by MiaomiaoCai** [comment]
110未发现此问题
