### ISSUE TITLE
当卡片较多时，长按卡片进入管理卡片的界面，界面顶部会自动进入向上滚动后的状态——top bar底部出现阴影，不应如此。详见附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#288]
![09b88e63-755f-41d0-807b-ac5f001ebe97](https://user-images.githubusercontent.com/14070164/45611536-4e830100-ba92-11e8-8b03-4bb7fa1d08f2.jpeg)

**Comment by angel-developer** [comment]
iOS 版本83解决。

**Comment by MiaomiaoCai** [comment]
110验证已修复
![image](https://user-images.githubusercontent.com/38175831/52849832-f2a9ca80-314c-11e9-8c43-38216f1e5b0d.png)
