### ISSUE TITLE
设备详情和城市详情界面的行动建议，每条建议左侧的图标的左起位置太靠右，请向左调整，不需要和它们上方的表示各项读数的污染水平的大圆点对齐。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#289]
![0a0b0f17-475c-4ff5-818e-55e644818b2b](https://user-images.githubusercontent.com/14070164/45611762-26e06880-ba93-11e8-8492-7d19b6148fc2.jpeg)

**Comment by angel-developer** [comment]
设计也修改。 iOS v1.1.0 （125）已更新成新的UI.

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56118586-d8e60180-5f9c-11e9-9e3b-d9a4fd5874b9.png)
iOS v141验证已修复

**Comment by nhoj0102** [comment]
安卓 (103)已验证修复
![B750EDB5FB775576FAE8967DAD69FDFA](https://user-images.githubusercontent.com/51428604/60170522-6de75100-97bd-11e9-9220-077f246523e5.jpg)
