### ISSUE TITLE
iOS，根据当前地理位置自动出现的城市空气质量卡片，出现了重复，不应如此。评论中有图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#29]
如题。
![img_1317](https://user-images.githubusercontent.com/14070164/40582428-59d001bc-61a9-11e8-861b-548973cce8d8.PNG)

**Comment by Jackacey** [comment]
如果去一个新城市，根据当前地理位置自动出现的卡片会增加一个，变成两个。应该一直只有一个。
![img_df314ca52268-1](https://user-images.githubusercontent.com/37140201/40587338-81ea97c8-6200-11e8-8798-7c9cc4068f3f.jpeg)
