### ISSUE TITLE
处于设备详情时，收到了一条其他app的通知，此时青萍空气app的设备详情界面顶部变成了白色，不应如此。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#293]
![f495f057-82cf-457b-be72-f8c0a3d19877](https://user-images.githubusercontent.com/14070164/45612219-e84bad80-ba94-11e8-8a71-1dd9bd3e740b.jpeg)

**Comment by angel-developer** [comment]
iOS 版本83解决。

**Comment by MiaomiaoCai** [comment]
85验证已修复
