### ISSUE TITLE
设备详情，读数名称“Temp”请改为“Temperature”、“RH”请改为“Humidity”，因为能显示下。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#295]
如题。

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64310416-91572500-cfd2-11e9-925a-c31213fc3fc8.png)
