### ISSUE TITLE
他人共享设备给我时，我看到的共享设备对话框上的文字、接受成功的文字的修改意见

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#297]
1. 英文 “xxx” share with you 请改为 “xxx” is sharing a device

2. 设备名称，请加上引号。

3. Accept Sharing 请改为 Accept

4. 接受成功的文字 Accept xxx successful 请改为 Accepted succesfully

**Comment by angel-developer** [comment]
版本68解决

**Comment by MiaomiaoCai** [comment]
iOS V110 验证已修复

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证修复
