### ISSUE TITLE
别人分享给我的设备，详情界面，“From “xxx””文字距离标题文字太近

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#299]
![pasted_image_2018_9_18__12_32_pm](https://user-images.githubusercontent.com/14070164/45664564-0d94f600-bb3f-11e8-80bd-40c6931aef86.jpg)

**Comment by angel-developer** [comment]
版本68解决

**Comment by Dongwei0516** [comment]
版本55修复

**Comment by MiaomiaoCai** [comment]
iOS V110，Android V74验证已修复
![image](https://user-images.githubusercontent.com/38175831/52847822-3948f600-3148-11e9-8713-59b4e01cea00.png)
![image](https://user-images.githubusercontent.com/38175831/52847850-482fa880-3148-11e9-83eb-a946c6416238.png)
