### ISSUE TITLE
同步Goose数据的toast优化

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#304]
在详情界面的蓝牙图标旁边显示状态：
- 正在寻找Goose并建立长连接时：连接中...
- 已建立长连接并开始同步数据时：正在同步... x%
- 完成同步后，不显示文字。
- 同步未完成：未连接 （也就是和一开始就没连上的文字一样）

简体中文：连接中...
繁体中文：連接中...
英文：Connecting...

简体中文：正在同步... x%
繁体中文：正在同步... x%
英文：Syncing... x%

X颗粒度为10%, x小于10时不显示“x%”。

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159  验证修复
