### ISSUE TITLE
iOS版，首次请求地理位置访问权限的对话框里的提示文字是“use location”，需要优化

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#308]
@angel-developer ，以后遇到这种需要填写用户可见的字符串的地方，都请先找 @GayoZhao ，不要自己填。

@GayoZhao 写好之后，先给我审核，再交给工程师。

**Comment by GuiYongZhao** [comment]
定位：需要访问您的位置，从而展示当前城市的空气质量和天气

相册：需要访问您的相册，从而保存图片

**Comment by angel-developer** [comment]
版本74解决。

**Comment by dubinbeta** [comment]
文字改一下， @GayoZhao @angel-developer 

地理位置：
简体：显示您当前所处城市的空气质量和天气。
繁体：显示您当前所處城市的空氣質量和天氣。
英文：Show the air quality and weather of current location.

相册：
简体：保存图片。
繁体：保存圖片。
英文：Save photos.

**Comment by angel-developer** [comment]
iOS 版本75解决。

**Comment by MiaomiaoCai** [comment]
110验证已修复
![image](https://user-images.githubusercontent.com/38175831/52611380-4a7fd180-2ec0-11e9-8fce-13cd0f054ac1.png)
