### ISSUE TITLE
iOS，主界面，缺少引导用户启用地理位置权限以显示当前所在城市的空气质量的UI

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#31]
如题。

<img width="1039" alt="screen shot 2018-05-27 at 12 34 00 pm" src="https://user-images.githubusercontent.com/14070164/40582458-446b286e-61aa-11e8-9f76-e22ada398030.png">

**Comment by MiaomiaoCai** [comment]
iOS V84验证已修复

**Comment by MiaomiaoCai** [comment]
Android 59验证已修复
