### ISSUE TITLE
“请长按温湿度计背面按钮 2 秒, 待屏幕上度蓝牙图标开始闪烁。”文字修改意见

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#318]
请改为：

中文：请长按温湿度计背面的按钮 2 秒

繁體：請長按溫濕度計背面的按鈕 2 秒

英文：Press and hold the button on the back of the temperature and humidity monitor for 2 seconds.

**Comment by angel-developer** [comment]
iOS 版本73解决。

**Comment by MiaomiaoCai** [comment]
iOS74验证已修复

**Comment by MiaomiaoCai** [comment]
Android V50验证已修复
