### ISSUE TITLE
英文，分享设备详情界面分享到社交网络的图片，文字和时间格式问题，评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#320]
![pasted_image_2018_9_27__11_20_pm](https://user-images.githubusercontent.com/14070164/46157071-84ec2780-c2ad-11e8-9f48-11f00f73900b.jpg)

**Comment by dubinbeta** [comment]
分享城市详情的图片，也应做相应的修改。

**Comment by dubinbeta** [comment]
补一条调整和一个问题：
![img_2215](https://user-images.githubusercontent.com/14070164/46221290-4030c100-c37f-11e8-8328-08d007dcfbfe.jpg)

**Comment by angel-developer** [comment]
iOS 版本85修复。

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by jiaruirui323** [comment]
Android v121验证未修复
![image](https://user-images.githubusercontent.com/52393989/64582390-15891e00-d3c0-11e9-9075-f7accbeddef8.png)
