### ISSUE TITLE
Goose或Snow的详情界面分享到社交网络的图片里的二维码，识别后访问的页面的问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#323]
@marsWu1989 

1. 分享Goose的详情到社交网络的图片上的二维码对应的URL，和分享Snow的二维码的，搞反了。

2. 见下图：
![img_2202](https://user-images.githubusercontent.com/14070164/46158942-96cfc980-c2b1-11e8-98f2-422d48528f34.jpg)

**Comment by dubinbeta** [comment]
另外，现在点击“下载”、“了解更多”（包括介绍设备的小卡片上的），都是去了cleargrass.com/air。

如果是在系统自带浏览器中打开，点击“下载”，应该：
- iOS：前往App Store下载页
- 中国境内IP的Android：下载apk文件
- 境外IP的Android：前往Google Play里的app详情页

如果是在微信内嵌浏览器中打开，点击“下载”，应该：
- iOS：前往App Store
- Android：前往应用宝里的app详情页

（在Android app未上线时，Android手机点击“下载”一律提示“暂未上线”。）

点击app介绍小卡片上的“了解更多”，应该前往cleargrass.com/air。

点击设备介绍小卡片上的“了解更多”，应该前往各设备的概述页。

**Comment by angel-developer** [comment]
版本73解决。Goose 和 Snow的分享页面的二维码已更正。

**Comment by dubinbeta** [comment]
问题没有解决，你们自己不测吗？

**Comment by MiaomiaoCai** [comment]
@marsWu1989 改好后请备注一下，我来验证

**Comment by marsWu1989** [comment]
@MiaomiaoCai 修复了，你看下

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/53949793-c3f89180-4105-11e9-8499-9840ce103f86.png)
![image](https://user-images.githubusercontent.com/38175831/53949808-ce1a9000-4105-11e9-8166-35851a47fce1.png)
验证已修复
