### ISSUE TITLE
iPhone SE，首页的Goose卡片右侧读数，超出卡片（Snow的读数也是如此）

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#325]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/46242745-e1ab2780-c3fe-11e8-82ed-a80542f06c99.jpg">

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by MiaomiaoCai** [comment]
@angel-developer 右侧读数顶到边界，请调整
![image](https://user-images.githubusercontent.com/38175831/47988417-1d7f8e00-e11d-11e8-82f2-871eb404a17e.png)

**Comment by angel-developer** [comment]
iOS v126 修复。iPhone 6 以上屏幕 间距不变， 小屏幕调整间距。
<img width="307" alt="屏幕快照 2019-03-19 下午4 05 18" src="https://user-images.githubusercontent.com/20908900/54589533-defdc680-4a60-11e9-8f62-2281f37a92e3.png">

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/55373887-3871f500-5539-11e9-918b-934ad1bb051a.png)
验证已修复
