### ISSUE TITLE
iOS, Goose设备详情界面的蓝牙图标太瘦（左右宽度小），可能被拉伸了

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#326]
如题

**Comment by angel-developer** [comment]
版本73解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/47987193-ecea2500-e119-11e8-9192-112d6dc818e5.png)
85验证已修复
