### ISSUE TITLE
设备管理，共享设备，列表不为空时的界面文字问题和UI调整意见，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#328]
![img_b1f22702aa2d-1](https://user-images.githubusercontent.com/14070164/46248563-4ee5a980-c44d-11e8-9486-668433f50e1f.jpg)

**另外，这个界面应支持整体滚动，而非已共享的人员列表滚动。**

**Comment by dubinbeta** [comment]
这个问题赶快改了，这个has shared太尴尬了。

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed. 字符提前转没有方法解决。

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
