### ISSUE TITLE
iOS，需研究苹果是否允许app内嵌网页内有购物功能（用于决策主界面的“现在购买”打开网页的方式）。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#33]
如题。

**Comment by GuiYongZhao** [comment]
目前锤子的畅呼吸 app 内嵌网页内有购物功能。

**Comment by dubiao** [comment]
但不建议用内嵌的网页，而使用浏览器打开。 @dubinbeta @GayoZhao 

购买要跳到商店，下单后有付款什么的，用浏览器可以完全把这件事抛给浏览器，包括用户后面可能会输入的密码之类的，也给了用户分享到其它用户或是Handoff到电脑操作的机会。也可以购买到一半回来操作app。

以及，如果这个是针对所有平台的，那么Android使用内嵌不知道会出什么问题；如果是只针对iOS的，那么Android是用浏览器打开，iOS也没什么不可以吧。

**Comment by dubinbeta** [comment]
支持直接打开浏览器，iOS和Android都是。
