### ISSUE TITLE
"Network Error ( 110 )“这样的提醒，请改为”Network Error 110“，中文也是。原因详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#331]
1. 括号里面的字符开头和末尾不需要加空格。
2. 为了一并省去在中英文状态下区分中英文括号的麻烦，干脆去掉括号，表意不受影响。。

**Comment by angel-developer** [comment]
iOS 版本75解决。

**Comment by MiaomiaoCai** [comment]
iOS V110验证已修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
Android V77，错误码与文字之间没有空格
![image](https://user-images.githubusercontent.com/38175831/54344731-7b4c5580-467c-11e9-88be-d51b12981707.png)

**Comment by Dongwei0516** [comment]
Android v78 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
