### ISSUE TITLE
iOS，英文，主界面，卡片上的文字底部被截断，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#332]
![img_54770d7a99ab-1](https://user-images.githubusercontent.com/14070164/46614224-dadf8b80-cb47-11e8-9d0d-b5e3a9cf1f0f.jpg)

**Comment by angel-developer** [comment]
iOS 版本75解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/48185543-3c299300-e370-11e8-85e7-0f5355bf91b4.png)

**Comment by MiaomiaoCai** [comment]
85验证已修复
