### ISSUE TITLE
手机蓝牙关闭，删除Goose卡片后，重新打开app，不应继续提示“打开蓝牙”

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#334]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/46710114-1af25b80-cc79-11e8-931b-81de23c96ffa.jpg">

**Comment by angel-developer** [comment]
iOS 版本83解决。

**Comment by MiaomiaoCai** [comment]
85验证已修复
