### ISSUE TITLE
添加Goose页面，英文提示需调整排版

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#336]
系统版本：iOS 74，Android 50
![image](https://user-images.githubusercontent.com/38175831/46732458-20bf5f80-ccc0-11e8-8aa5-44a4e88b2ea5.png)

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/46732891-4f8a0580-ccc1-11e8-9a44-480803ee7235.png)

**Comment by angel-developer** [comment]
iOS 版本75解决。

**Comment by MiaomiaoCai** [comment]
iOS V82验证已修复
![image](https://user-images.githubusercontent.com/38175831/47196186-f477a300-d391-11e8-80b5-dfced8a64874.png)

**Comment by Dongwei0516** [comment]
Android 55版本已修复

**Comment by MiaomiaoCai** [comment]
验证已修复
