### ISSUE TITLE
设置，通知，界面上的英文字符串修改意见，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#340]
![img_2391](https://user-images.githubusercontent.com/14070164/46905335-cb37bc80-cf24-11e8-9db3-782a6fc66c0f.jpg)

**Comment by angel-developer** [comment]
iOS 版本81解决。

**Comment by MiaomiaoCai** [comment]
iOS V82验证已修复

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android 该页面修改参考https://github.com/ClearGrass/Air-App-Issues/issues/416
