### ISSUE TITLE
登出对话框的英文字符串的问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#341]
![img_2392](https://user-images.githubusercontent.com/14070164/46905357-25388200-cf25-11e8-821e-52f5d73be158.jpg)

**Comment by angel-developer** [comment]
iOS 版本81解决。

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 Android V52，没有‘WeChat’，并且‘CANCEL’和'OK'按钮与上图不一致
![image](https://user-images.githubusercontent.com/38175831/47427651-94cf2c80-d7c3-11e8-94f5-8ac0811e37f3.png)

**Comment by Dongwei0516** [comment]
@MiaomiaoCai 按钮是安卓系统样式，不需要与iOS一致

**Comment by MiaomiaoCai** [comment]
Android V75验证已修复
![image](https://user-images.githubusercontent.com/38175831/53877449-2426ff00-4044-11e9-91ba-9213512997e3.png)
