### ISSUE TITLE
城市详情，有限行政策，但当前不限行时，英文“Not limited”请改为“None”

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#342]
![img_2394](https://user-images.githubusercontent.com/14070164/46905403-b90a4e00-cf25-11e8-9bf9-0dfff8f57cf0.jpg)

**Comment by angel-developer** [comment]
iOS 版本81解决。

**Comment by MiaomiaoCai** [comment]
iOS V84验证已修复

**Comment by Dongwei0516** [comment]
Android v57解决

**Comment by MiaomiaoCai** [comment]
Android V75验证已修复
