### ISSUE TITLE
正在升级Goose时，点击左上角的返回按钮，弹出的提示对话框的文字修改意见

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#343]
1. 英文文字请改为：Go back now will cause the update to fail, are you sure you want to go back?
2. 红色的“OK”请改为蓝色的“Confirm”。如果中文的也是“OK”，请改为蓝色的“确认”。

**Comment by angel-developer** [comment]
iOS 版本83修改。

**Comment by MiaomiaoCai** [comment]
@angel-developer V110验证，第2条未实现，请用"Confirm"替代“OK”
![image](https://user-images.githubusercontent.com/38175831/52847267-acea0380-3146-11e9-8ed8-87f39818ea52.png)

**Comment by angel-developer** [comment]
iOS v144 修复， 修改参考 issue #557

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58320142-9a6e1d00-7e4d-11e9-9eb0-7a4127fb8f9f.png)
iOS V144验证已修复
