### ISSUE TITLE
导出设备历史数据，输入email地址的界面，字符串中的设备名没有正确显示，英文字符串需要修改，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#345]
![pasted_image_2018_10_13__8_53_pm](https://user-images.githubusercontent.com/14070164/46905752-9464a500-cf2a-11e8-9fed-9e4edb9c5044.jpg)

**Comment by angel-developer** [comment]
iOS 版本81解决。

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by Dongwei0516** [comment]
Android 版本55已修复

**Comment by MiaomiaoCai** [comment]
验证已修复
