### ISSUE TITLE
导出设备历史数据，输入email地址，成功提交后的提示，应使用类似升级固件成功后的界面，而非弹一个toast。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#346]
界面上显示一个对号，下面的文字是：

简体：已发送
繁体：已發送
英文：Sent

**Comment by angel-developer** [comment]
iOS 版本83解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/47982683-9c6bcb00-e10b-11e8-9ca3-99669770b1ea.png)
iOS 85验证已修复

**Comment by dubinbeta** [comment]
“确定”请改为“完成”。

**Comment by Dongwei0516** [comment]
Android v79 已修复。

**Comment by MiaomiaoCai** [comment]
Android V81验证，仍然显示toast

**Comment by Dongwei0516** [comment]
Android v90 修复。

**Comment by MiaomiaoCai** [comment]
Android V103验证已修复
![image](https://user-images.githubusercontent.com/38175831/60248528-6dea6c80-98f5-11e9-8d73-a3696a5d64fd.png)
