### ISSUE TITLE
分享设备到社交网络的图的问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#348]
![pasted_image_2018_10_13__10_25_pm](https://user-images.githubusercontent.com/14070164/46906602-a0effa00-cf38-11e8-9553-5cffcc3bc60b.jpg)

**Comment by angel-developer** [comment]
iOS 版本 81解决。

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by MiaomiaoCai** [comment]
@Dongwei0516  Android V53 UI 第二条没有显示行动建议，第三条没有使用”·“作为分隔符

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64595130-e97f9400-d3e3-11e9-862a-930c83952f12.png)
