### ISSUE TITLE
共享设备，发送到微信对话内的气泡，上面的文字的修改意见，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#349]
只改中文的，英文的是OK的：
![pasted_image_2018_10_13__10_49_pm](https://user-images.githubusercontent.com/14070164/46906720-aa7a6180-cf3a-11e8-84f5-fedbebd58baa.jpg)

**Comment by angel-developer** [comment]
iOS 版本81解决。

**Comment by MiaomiaoCai** [comment]
@angel-developer @GayoZhao  “向您共享”英文请使用“Sharing with you”，iOS 85

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by Dongwei0516** [comment]
Android 版本55修复

**Comment by MiaomiaoCai** [comment]
71验证已修复
