### ISSUE TITLE
snow设备详情页五个读值都显示“--”

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#353]
V1.0.0，华为honor8
备注：首页设备卡片读数正常
![image](https://user-images.githubusercontent.com/38175831/47137950-a65b9480-d2ea-11e8-8903-6a9f62e16948.png)

**Comment by MiaomiaoCai** [comment]
三星note9也会偶现此问题

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
