### ISSUE TITLE
添加Goose成功后，app端读数显示“--“

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#357]
V0.5.0，三星note3
![image](https://user-images.githubusercontent.com/38175831/47144664-8207b400-d2fa-11e8-8347-0e215bef2e45.png)

**Comment by Dongwei0516** [comment]
Android v90 修复。

**Comment by MiaomiaoCai** [comment]
Android v91验证已修复
