### ISSUE TITLE
温湿度读数解释错误

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#358]
V0.5.0
![image](https://user-images.githubusercontent.com/38175831/47149816-49baa280-d307-11e8-8fed-5ef42f407b9a.png)
![image](https://user-images.githubusercontent.com/38175831/47149833-54753780-d307-11e8-9fbc-0bc4a9c7825c.png)

**Comment by Dongwei0516** [comment]
版本55已修复

**Comment by MiaomiaoCai** [comment]
验证已修复
