### ISSUE TITLE
读数解释页，参考标准不可选 

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#359]
V0.5.0

**Comment by Dongwei0516** [comment]
版本55已修复

**Comment by MiaomiaoCai** [comment]
55验证未修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54345041-31b03a80-467d-11e9-8a8b-4cd7317e6f61.png)
V77验证，从中国标准切换到美国标准，返回后入口处仍显示中国标准

**Comment by Dongwei0516** [comment]
Android v90 修复。

**Comment by MiaomiaoCai** [comment]
Android v91验证已修复
