### ISSUE TITLE
主界面、设备详情界面，未连接时间超过2小时时，字符串“x hour”应为“x hours”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#361]
如题。
![img_2517](https://user-images.githubusercontent.com/14070164/47414966-ddc3b880-d7a4-11e8-90fa-c6f7fff56064.jpg)

**Comment by angel-developer** [comment]
iOS 版本84修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/48248977-69d81000-e434-11e8-98df-69e043c90810.png)
@angel-developer 86验证首页设备卡片未修改

**Comment by angel-developer** [comment]
iOS  v1.0.8 94 解决。

**Comment by MiaomiaoCai** [comment]
iOS 94验证已修复

**Comment by MiaomiaoCai** [comment]
Android V103验证已修复
![image](https://user-images.githubusercontent.com/38175831/60313033-1947ff80-9990-11e9-8279-84d13c35e83a.png)
![image](https://user-images.githubusercontent.com/38175831/60313042-1f3de080-9990-11e9-8ac9-165ec7aef5fa.png)
