### ISSUE TITLE
读数解读界面的文字大小和间距的问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#367]
![img_2539](https://user-images.githubusercontent.com/14070164/47645592-721a8a80-dbac-11e8-83a7-f4a61206d4d1.jpg)

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/48243372-10171c00-e41b-11e8-8dcb-9e0637df899d.png)

**Comment by MiaomiaoCai** [comment]
iOS 85验证已修复

**Comment by MiaomiaoCai** [comment]
Android V103验证已修复
![image](https://user-images.githubusercontent.com/38175831/60324250-ea914f80-99b6-11e9-8f21-ab8737a7370d.png)
