### ISSUE TITLE
iOS版app，添加Snow后转到Snow详情界面，在已获得历史数据的情况下，没显示实时数据，不应如此

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#368]
![img_2563](https://user-images.githubusercontent.com/14070164/47661325-c84ef400-dbd3-11e8-8bd3-52e8b8b7aa98.PNG)

**Comment by dubinbeta** [comment]
同时，界面显示设备未连接，需要等很久（约20秒）才能变为已连接并显示数据。不应如此，应立即显示为已连接，并显示数据。

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) Snow没有实时数据是，会先展示服务器保存的心跳数据。

**Comment by MiaomiaoCai** [comment]
V110验证未发现此问题
