### ISSUE TITLE
iOS，Snow设备详情，剩余电量和未连接图标摞在一起了

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#370]
![23e413ae-ecc9-48b2-9d85-7e0dc7f534b0](https://user-images.githubusercontent.com/14070164/47692366-535dd780-dc30-11e8-92f2-ed1da55c9c50.jpg)

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by MiaomiaoCai** [comment]
iOS 85未连接时，已去掉电池电量图标
