### ISSUE TITLE
主界面，卡片上的小圆点和设备icon的对齐问题，详见附件

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#371]
![img_2523](https://user-images.githubusercontent.com/14070164/47692855-3a562600-dc32-11e8-96ca-8b847b068f16.jpg)

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by MiaomiaoCai** [comment]
iOS85验证已修复
