### ISSUE TITLE
英文，设备详情，设备管理，固件更新，无更新时界面上显示的按钮“Check Update”，文字请改为“Check for Updates”。另，当点击该按钮后，显示正在检查更新的动画时，文字请改为“Checking for Updates”，注意：文字变长了，动画不要盖在文字上。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#373]
如题。

**Comment by angel-developer** [comment]
iOS 版本85解决。

**Comment by MiaomiaoCai** [comment]
iOS V85验证已修复

**Comment by Dongwei0516** [comment]
Android v65 已修复

**Comment by MiaomiaoCai** [comment]
@Dongwei0516 ，“Check for Updates”不需要都是大写，另外点击此按钮，没有检查更新的动画
![image](https://user-images.githubusercontent.com/38175831/50808786-2538fa00-133b-11e9-97de-85d8eea47265.png)
