### ISSUE TITLE
主界面，从大字显示“青萍空气”文字和logo切换为在左上角小字显示文字和logo的时机，需调整，详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#38]
目前是在大字显示“青萍空气”文字和logo时如显示不下所有的卡片和加号，就切换为在左上角小字显示logo和文字，这样有个问题：切换后界面底部可能太空。如下图所示：
![img_1321](https://user-images.githubusercontent.com/14070164/40582991-64dacd68-61b7-11e8-9def-4c89aaa416a4.PNG)

所以，请不要考虑加号是否能被显示出来，当能显示完所有的卡片但无法显示完加号按钮时，仍应保持大幅显示“青萍空气”文字和logo的样式。

另外，请缩小加号图标的直径，让它和大字显示“青萍空气”时的logo的直径相同。

**Comment by MiaomiaoCai** [comment]
iOS V 84，Android V52验证已修复
