### ISSUE TITLE
设备详情界面，上次更新时间文字距离屏幕左边缘、“未连接”文字距离屏幕右边缘，不相等，应该相等。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#381]
![img_2666](https://user-images.githubusercontent.com/14070164/48342710-626e6c00-e6ab-11e8-8c71-7438ea7a97b1.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.7 92 修复。

**Comment by MiaomiaoCai** [comment]
100验证已修复

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
Android V103验证未修复
![image](https://user-images.githubusercontent.com/38175831/60333569-f5a2aa80-99cb-11e9-9ecf-b020e37e752d.png)
![image](https://user-images.githubusercontent.com/38175831/60333650-297dd000-99cc-11e9-85d2-3bb0f7eafbf3.png)

**Comment by Dongwei0516** [comment]
Android v104 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64519441-b1fee200-d326-11e9-8a85-c9c64bb89293.png)
