### ISSUE TITLE
Goose详情界面，正在连接文字右侧应有蓝牙图标。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#382]
![img_2672](https://user-images.githubusercontent.com/14070164/48343183-aa41c300-e6ac-11e8-989c-18d6ccaf96c9.jpg)

如题。

**Comment by dubinbeta** [comment]
注意蓝牙图标和“正在连接...”文字之间应有一个空格的间距。

**Comment by angel-developer** [comment]
iOS v1.0.7 92 修复。

**Comment by dubinbeta** [comment]
实测没有解决。

**Comment by angel-developer** [comment]
iOS v1.0.8 95 解决。

**Comment by MiaomiaoCai** [comment]
iOS V108验证已修复
![image](https://user-images.githubusercontent.com/38175831/51902018-fcfd6200-23f3-11e9-9b15-937ec21c80c9.png)

Android V74验证已修复
![image](https://user-images.githubusercontent.com/38175831/51902074-1c948a80-23f4-11e9-9009-95c992d07407.png)
