### ISSUE TITLE
请将界面上的文字“湿度”改为“相对湿度”（繁体改为“相對濕度”）。因为“湿度”经常被看成“温度”。英文不用改。

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#383]
如题。

**Comment by angel-developer** [comment]
iOS 版本87修改。

**Comment by angel-developer** [comment]
iOS v1.0.7 92 修改。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/49915092-e005e180-fece-11e8-8511-d470c42314fd.png)
@angel-developer 此处未使用相对湿度

**Comment by angel-developer** [comment]
iOS v1.0.9 (96)修改；修改地方 snow 分享Snow设备的描述， Goose分享Goose设备的描述，温湿度坐标显示。

**Comment by Dongwei0516** [comment]
Android v65 解决。

**Comment by MiaomiaoCai** [comment]
iOS 100，Android 65验证已修复
