### ISSUE TITLE
通知目前还没有英文，应有。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#384]
![img_2733](https://user-images.githubusercontent.com/14070164/48632169-705b1000-e97d-11e8-97e8-cb1e10dc1a62.PNG)

**Comment by dubinbeta** [comment]
仅当用户设备语言是非简体中文、繁体中文时，下发英文通知。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/49915562-3d029700-fed1-11e8-956c-b99de6b65739.png)
验证已修复
