### ISSUE TITLE
Snow的固件更新界面的一系列问题，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#385]
1. 下图中的“Update Now”应改为：
- 英文：Download
- 简体：下载
- 繁体：下載
<img width="272" alt="screen shot 2018-11-16 at 9 17 10 am" src="https://user-images.githubusercontent.com/14070164/48633375-671f7280-e980-11e8-86c0-3d8328523433.png">

2. 正在下载固件时，
- 图标的方向应该调过来。
- 文字应该改为
 -- 简体：正在下载...
 -- 繁体：正在下載...
 -- 英文：Downloading...
<img width="270" alt="screen shot 2018-11-16 at 9 20 05 am" src="https://user-images.githubusercontent.com/14070164/48633551-cf6e5400-e980-11e8-95ec-e129a82537bb.png">

3. 正在下载时，返回上一级别界面，应可重新进入查看进度，现在不可以。

4. 下载成功后，图中的“Confirm”应改为：
- 英文：OK
- 简体：好的
- 繁体：好的
<img width="269" alt="image" src="https://user-images.githubusercontent.com/14070164/48633447-8f0ed600-e980-11e8-861e-8e5621ddc00a.png">

**Comment by angel-developer** [comment]
iOS v1.0.8 91 解决。

**Comment by MiaomiaoCai** [comment]
@angel-developer 94验证第2条未修复

**Comment by angel-developer** [comment]
iOS v1.0.9 （96）下载 图标已更正。

**Comment by MiaomiaoCai** [comment]
@angel-developer V110验证，文案仍然是“Updating……”，请使用“Downloading……”
![image](https://user-images.githubusercontent.com/38175831/52624081-e02f5700-2ee8-11e9-8767-dd1b07b0cea3.png)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58413679-fb932c00-80ab-11e9-85ae-9ec76bb1a3d6.png)
@肖贝贝，@宁志强，@董威，请添加一个Snow的设备缩略图
