### ISSUE TITLE
添加Goose的界面，可以把”现在购买“按钮加回去了

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#387]
点击按钮，跳出app，用浏览器打开”https://store.cleargrass.com/products/cg-temp-rh-monitor“。

**Comment by angel-developer** [comment]
Snow 添加界面是否需要添加购买链接 @dubinbeta @GayoZhao

**Comment by angel-developer** [comment]
iOS v1.0.7 92解决。

**Comment by GuiYongZhao** [comment]
> Snow 添加界面是否需要添加购买链接 @dubinbeta @GayoZhao

Snow还没有开卖，待开卖后，再加上。

**Comment by MiaomiaoCai** [comment]
iOS 94验证，添加goose的页面已添加

**Comment by angel-developer** [comment]
iOS v1.1.0 (118) 修复， 还添加了购买设备功能。

**Comment by MiaomiaoCai** [comment]
验证已修复
![image](https://user-images.githubusercontent.com/38175831/53940654-27c48f80-40f1-11e9-9e3c-e1a4e37db4d5.png)
