### ISSUE TITLE
导出读数历史的界面，输入email地址的界面，英文字符问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#390]
如题。
![img_2902](https://user-images.githubusercontent.com/14070164/48996339-b9357480-f186-11e8-8a3d-ac633fd9e0da.jpg)

注意：“E-mail”这种写法已经太老旧了，“email”已经成为规范用语，以后请使用“email”（在首字母需要大写的情形下大写首字母）。“Mail”有和实体邮件混淆（虽然可能性极低）的可能性。

**Comment by dubinbeta** [comment]
另外，要注意字符串的用法的连贯性，在“联系我们”里，输入电子邮件或电话号码的框内的文字是“You email or phone number”，所以导出CSV这里用“Your email”。

**Comment by angel-developer** [comment]
杜老师， 上面红色文字对应的中文、繁体是否需要修改。 @GayoZhao  @dubinbeta

**Comment by dubinbeta** [comment]
中文简体：历史数据 CSV 文件将通过电子邮件发送给您。
中文繁体：歷史數據 CSV 文件將通過電子郵件發送給您。

**Comment by dubinbeta** [comment]
中文，输入框中的占位文字不需要修改。

**Comment by angel-developer** [comment]
iOS v1.0.7 91解决。

**Comment by MiaomiaoCai** [comment]
@angel-developer 中文繁体，输入框请使用“電子郵件”
![image](https://user-images.githubusercontent.com/38175831/49360796-290ea680-f715-11e8-8f2f-8db16981643a.png)

**Comment by angel-developer** [comment]
iOS v1.0.7 93 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/49436921-49ae2d80-f7f5-11e8-9744-0bc73bc22e40.png)
![image](https://user-images.githubusercontent.com/38175831/49436931-503ca500-f7f5-11e8-8950-4136caa2122c.png)
@Dongwei0516  英文时，输入框请使用“Your email”繁体中文时，请使用“電子郵件”

**Comment by MiaomiaoCai** [comment]
iOS 94验证已修复

**Comment by dubinbeta** [comment]
“提交”请改为“发送”。
繁体：發送
英文：Send

**Comment by Dongwei0516** [comment]
Android v65 解决。

**Comment by MiaomiaoCai** [comment]
验证已修复
