### ISSUE TITLE
添加HomeKit版Goose的选单中的英文错误（这个设备的英文名错误）

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#391]
中文：青萍蓝牙温湿度计 HomeKit 版
繁体：青萍藍牙溫濕度計 HomeKit 版
英文：ClearGrass Temperature and Humidity Monitor for HomeKit
![pasted_image_2018_11_26__3_43_pm](https://user-images.githubusercontent.com/14070164/48999837-c3f60680-f192-11e8-8f2f-3e96dda48fad.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.7 92 修正字符串。 文字提前换行暂无解决方法。

**Comment by MiaomiaoCai** [comment]
HomeKit版Goose相关功能的代码目前暂被删除，此issue失效
