### ISSUE TITLE
iOS，Widget，英文，设备列表，为空时应显示“No device added”文字，现在没有文字

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#401]
![img_2933](https://user-images.githubusercontent.com/14070164/49328862-1596fa80-f5b2-11e8-87e3-d3f7f7f3699a.PNG)

**Comment by angel-developer** [comment]
iOS v1.0.7 93修复。

**Comment by MiaomiaoCai** [comment]
94验证已修复
