### ISSUE TITLE
通知地名错误，详见评论附图。1. “Suzhou”应该是“Suzhou, Jiangsu”；2. 不应2次通知不一样。 

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#402]
如题。
![img_2937](https://user-images.githubusercontent.com/14070164/49328907-cef5d000-f5b2-11e8-8aad-feb99ef018b4.PNG)

**Comment by MiaomiaoCai** [comment]
验证已修复
