### ISSUE TITLE
导出历史数据，收到的邮件，CSV文件名错误。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#403]
姜洋在群里的反馈。
![_fb1e8a05-323f-4007-9325-509ec566bbc2](https://user-images.githubusercontent.com/14070164/49336603-7ec54f00-f640-11e8-85c2-450abb33f327.png)

**Comment by MiaomiaoCai** [comment]
@guoyanjun5 验证未修复
![image](https://user-images.githubusercontent.com/38175831/50269029-e0baec80-0467-11e9-9236-b9db45084d94.png)
