### ISSUE TITLE
在不支持的城市打开app时，应隐藏当前城市卡片（但设置里的开关保持原状）、添加城市时的待选城市界面的当前定位城市按钮可以显示“[定位图标]未知”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#404]
中文简体：未知
中文繁體：未知
英文：Unknown

如有问题，请找我商量。

![_637145f8-4725-468b-b016-a1430b12cba4 1](https://user-images.githubusercontent.com/14070164/49336612-a7e5df80-f640-11e8-8e71-a7cfc69904bd.png)

**Comment by angel-developer** [comment]
iOS v1.0.8 94解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/53864965-d18c1980-4028-11e9-8b24-b87242fdd2cf.png)
iOS V1.0.9，托前同事在泰国截的图

**Comment by dubinbeta** [comment]
@MiaomiaoCai ，赞！
