### ISSUE TITLE
iOS，手机系统语言设为英文，城市相关通知是英文，Snow相关通知仍是中文，不应如此。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#405]
![img_2962](https://user-images.githubusercontent.com/14070164/49588707-718ec400-f9a2-11e8-96a1-6510ed6aafba.PNG)

**Comment by dubinbeta** [comment]
没有fix，请看下图：
![img_3041](https://user-images.githubusercontent.com/14070164/50262995-b446a680-044e-11e9-9426-6d8f4c2f7297.jpg)

**Comment by dubinbeta** [comment]
没有fix， @guoyanjun5 看到了吗？

**Comment by server-go** [comment]
已修复
