### ISSUE TITLE
iOS，英文，Widget，城市名称显示格式错误，不应是“Chaoyang - Beijing”，应是“Chaoyang, Beijing”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#406]
如题。
![img_2980](https://user-images.githubusercontent.com/14070164/49693899-74fc9800-fbba-11e8-8f89-3cc58aad76b2.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.7 94 解决。

**Comment by MiaomiaoCai** [comment]
验证已修复
