### ISSUE TITLE
设置-设备和城市（或在主界面长按条目进入管理状态），删掉所有的条目后（或之前就为空时），应有文字说明。详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#41]
简体中文：没有空气设备或城市
繁体中文：沒有空氣設備或城市
英文：No air devices or cities

**Comment by GuiYongZhao** [comment]
此页面不会为空，因为有定位城市。定位城市不会被删除，只有开和关两种状态。

附图：

![image](https://user-images.githubusercontent.com/37681560/40699175-7b1f757e-6405-11e8-9037-56e9b14288ce.png)
