### ISSUE TITLE
Android，分享设备读数的图片的一系列问题，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#411]
![img_2986](https://user-images.githubusercontent.com/14070164/49714011-24527100-fc86-11e8-8dc8-27cc2062e73b.jpg)

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58067847-84e4c300-7bc1-11e9-8677-5777fcb28b8d.png)
Android V94验证，间距还是有点宽

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证未修复
![image](https://user-images.githubusercontent.com/52393989/64518183-4d428800-d324-11e9-88ac-db71b839e50f.png)
