### ISSUE TITLE
Widget的样式问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#415]
![wechatimg21333](https://user-images.githubusercontent.com/14070164/49934840-6b509880-ff0a-11e8-9500-f1be8a1537ae.jpg)

**Comment by dubinbeta** [comment]
增加一个问题：
![img_3029](https://user-images.githubusercontent.com/14070164/49981897-232a8800-ff95-11e8-86c5-a1c17b0118b7.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.8 95 将时间拒右侧距离和设备名字拒左边距离一样。
横线高度一像素， 已经最窄了。应该是颜色太深了。 @GayoZhao  查看怎么修改。

**Comment by GuiYongZhao** [comment]
> iOS v1.0.8 95 将时间拒右侧距离和设备名字拒左边距离一样。
> 横线高度一像素， 已经最窄了。应该是颜色太深了。 @GayoZhao 查看怎么修改。

那就把线调浅一些。

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51668865-1a9a8800-1ffe-11e9-89c8-411a48b2328a.png)
iOS 106 此处未修改
