### ISSUE TITLE
App全局设置、设备设置等界面，界面上的小标题，英文，应改为首字母大写，以区别于说明性文字。详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#416]
<img width="815" alt="screen shot 2018-12-13 at 7 18 50 pm" src="https://user-images.githubusercontent.com/14070164/49935524-2af21a00-ff0c-11e8-9bd0-61deb109346a.png">

**Comment by dubinbeta** [comment]
更新：小标题文字请改为全部字母大写，就像iOS系统那样。

**Comment by angel-developer** [comment]
v1.0.8 95 更改小标题内容：
单位设置界面、 小组件城市和设备界面、通知界面。

**Comment by MiaomiaoCai** [comment]
iOS V 106 验证已修复

**Comment by jiaruirui323** [comment]
Android 验证未修复
![image](https://user-images.githubusercontent.com/52393989/64100948-4f926880-cd9f-11e9-9380-a70872882633.png)

**Comment by jiaruirui323** [comment]
Android v120   验证未修复      
参考下图ios
![image](https://user-images.githubusercontent.com/52393989/64101158-cc254700-cd9f-11e9-86e7-a9d673c9b0fa.png)
