### ISSUE TITLE
分享设备，选择分享方式时，界面上被盖住的部分，太黑了，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#417]
![img_3022](https://user-images.githubusercontent.com/14070164/49935666-9b00a000-ff0c-11e8-8f92-9b8fd75f1f53.jpg)

**Comment by angel-developer** [comment]
透明度降低50%， 稍后请 @GayoZhao 查看。

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51590049-ab506580-1f23-11e9-9cd7-9d2a1e22b4c6.png)
106验证已修复
