### ISSUE TITLE
设备管理界面，提交反馈，界面上的设备名称文字，底部被切掉了一部分，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#418]
![img_3023](https://user-images.githubusercontent.com/14070164/49935727-cbe0d500-ff0c-11e8-9bd8-198ecc895258.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.8 95解决。

**Comment by MiaomiaoCai** [comment]
iOS 100验证已修复

**Comment by MiaomiaoCai** [comment]
Android 65，问题反馈页面，未显示设备名称
![image](https://user-images.githubusercontent.com/38175831/50883645-9fdd4480-1423-11e9-99c7-34d42ad20bc9.png)

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64502090-cd51f900-d2f6-11e9-87e2-babe00dcff4b.png)
