### ISSUE TITLE
Snow，设备管理，发现新版，新版更新说明文本框的问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#419]
![img_3026](https://user-images.githubusercontent.com/14070164/49942310-ea9c9700-ff1f-11e8-83db-e5625d8bb87b.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51244780-e7824400-19c0-11e9-8908-b1cc1c4b6798.png)
验证已修复
