### ISSUE TITLE
主界面，删掉所有的城市和设备后，底部没有自动出现“没有空气设备？‘现在购买’”，得先去一趟其他界面，返回后才会出现。不应如此，应在删除所有条目后立即出现。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#42]
如题。

**Comment by MiaomiaoCai** [comment]
iOS V111，主界面点击加号，最后一行显示购买设备的入口，此issue失效
![image](https://user-images.githubusercontent.com/38175831/53314729-db13d400-38fa-11e9-9b19-236d67f8e5a0.png)
