### ISSUE TITLE
添加青萍空气监测仪，界面上应有“现在购买”链接

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#43]
如题。

**Comment by GuiYongZhao** [comment]
具体的时机是？

**Comment by dubinbeta** [comment]
不需要时机，总是有。 @GayoZhao

**Comment by GuiYongZhao** [comment]
![image](https://user-images.githubusercontent.com/37681560/40596484-beafe5ec-626d-11e8-84a1-be7445896b8b.png)
是在这个页面添加“现在购买”链接？

**Comment by dubinbeta** [comment]
对。如下图:
<img width="357" alt="screen shot 2018-05-28 at 7 05 41 pm" src="https://user-images.githubusercontent.com/14070164/40611734-2bc72442-62aa-11e8-946f-3bad84b7c609.png">
