### ISSUE TITLE
英文，设备某项读数过高的通知，文字中缺少空格，详见附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#431]
![img_3030](https://user-images.githubusercontent.com/14070164/49988601-5a5b6200-ffb2-11e8-9af1-8842159525c8.jpg)

请检查其他通知是否也存在类似问题。

**Comment by MiaomiaoCai** [comment]
验证已修复
![image](https://user-images.githubusercontent.com/38175831/53942276-4e84c500-40f5-11e9-9e3d-a3cfadee8ca3.png)
