### ISSUE TITLE
iOS，分享设备详情页后，设备名称显示不全

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#432]
![image](https://user-images.githubusercontent.com/38175831/50279117-d575ba00-0483-11e9-915f-50bd02576fc7.png)

名称开头的字符“23……”未显示

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 修改。名字长度显示过长时，显示XXXX....

**Comment by MiaomiaoCai** [comment]
验证已修复
