### ISSUE TITLE
Android，分享设备详情页后，设备名称UI需调整

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#433]

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/50279595-1d491100-0485-11e9-9990-500a6b13a2fa.png)

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64089657-ac7b2800-cd79-11e9-9a02-56c8198baa23.png)
