### ISSUE TITLE
请去掉主界面的折叠行动建议的功能，现在不好点击，就算好点击，意义也不是很大，有设置中的是否显示的开关就足够了

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#434]
如题。

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
iOS V105验证已修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54346439-00853980-4680-11e9-9c0e-0842cf00b596.png)
Android V77验证已去掉
