### ISSUE TITLE
修改设备名称的界面，左上角应该是x，目前是返回。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#435]
如题。

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64247067-a5524680-cf40-11e9-82f9-537341bee761.png)
