### ISSUE TITLE
带有小标题的设置界面，小标题文字、说明文字与其他元素的间距问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#436]
![img_3047](https://user-images.githubusercontent.com/14070164/50374990-73f34e00-0631-11e9-9de8-54fcd40fa4b0.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51240459-b56be480-19b6-11e9-8295-d80db9833fed.png)
v105验证已修复
