### ISSUE TITLE
主界面和详情界面的“行动建议”中英文文字的显示方式调整建议，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#439]
![img_3049](https://user-images.githubusercontent.com/14070164/50375046-5ffc1c00-0632-11e9-9bc4-09f58c4c1713.jpg)

主界面的也做如此调整。

**Comment by angel-developer** [comment]
iOS v1.0.9 (96)解决。

**Comment by MiaomiaoCai** [comment]
iOS 106验证已修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54346551-3f1af400-4680-11e9-80f5-e0f51b58807c.png)
Android V77 验证已修复
