### ISSUE TITLE
iOS，为什么“当前网络可用”这个提示总是出现，不应出现。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#44]
如题。

**Comment by GayoZhao** [comment]
这个是开发为了检验 app 是否连上了服务器。

**Comment by angel-developer** [comment]
这是给APP做的一个断网监测机制，当网络状态 切换时会 给于应用提醒， 当前APP断网 会提示“ 当前网络不可用”，APP切换移动网络时 会提示 “当前网络可用”， 切换wifi 时  会提示 “当前网络可用”
