### ISSUE TITLE
城市详情界面的AQI和天气的可点击展开的区域的调整建议，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#440]
![img_3050](https://user-images.githubusercontent.com/14070164/50375113-4effda80-0633-11e9-85c2-0167aa39f019.jpg)

另外，Tomorrow后面要加个冒号，即变成：
- Tomorrow: AQI 13 [图标] 46
- Tomorrow: -8° [图标] 2°

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
iOS 97验证已修复

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58061810-66bf9880-7baa-11e9-8f55-86abf3f4c0f7.png)
Android v94验证，明天后面需要加冒号

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证未修复
![image](https://user-images.githubusercontent.com/52393989/64515947-25512580-d320-11e9-9b6b-03672a30cffd.png)
