### ISSUE TITLE
Widget中的城市列表和设备列表卡片上的分割线调整意见，详见评论附图

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#441]
![img_3051](https://user-images.githubusercontent.com/14070164/50380838-6204c000-06b0-11e9-9fb6-4ae41d2e20ae.jpg)

**Comment by angel-developer** [comment]
iOS v1.0.9 (96) 解决。

**Comment by MiaomiaoCai** [comment]
iOS 97验证已修复
