### ISSUE TITLE
提交完反馈后的成功界面上的“Confirm”请改为“OK”。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#442]
如题。

**Comment by angel-developer** [comment]
iOS  v1.1.0 (118) 修复。

**Comment by MiaomiaoCai** [comment]
iOS V122验证已修复
![image](https://user-images.githubusercontent.com/38175831/54099821-2697a900-43f6-11e9-8bc5-1ab066c2aeeb.png)

**Comment by Dongwei0516** [comment]
Android v77 Fixed。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54346800-ae90e380-4680-11e9-979e-e79baf851c57.png)
Android V77 验证已修复
