### ISSUE TITLE
tVOC正在初始化时，设备卡片页字符有重叠

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#446]
![wechatimg283](https://user-images.githubusercontent.com/14070164/51295476-c833f700-1a52-11e9-8fa4-60166e7434e2.jpg)

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/50681005-caef1f00-1044-11e9-8379-0b2ee2896b38.png)

**Comment by dubinbeta** [comment]
可以把“正在初始化...”换行显示，让tVOC和相对湿度所在的这一行变高。

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
Android V94验证，需调小字体，且左对齐
![image](https://user-images.githubusercontent.com/38175831/58067035-64ffd000-7bbe-11e9-8ceb-96984a58d766.png)

**Comment by jiaruirui323** [comment]
Android v120 验证未修复 需调小字体，且左对齐
![image](https://user-images.githubusercontent.com/52393989/64089356-47730280-cd78-11e9-8868-ffdb2aa30f37.png)

**Comment by jiaruirui323** [comment]
Android v120 Snow 详情页CO2和相对湿度间距过小
![image](https://user-images.githubusercontent.com/52393989/64089414-8a34da80-cd78-11e9-92af-fae790b1e28f.png)
