### ISSUE TITLE
iOS，修改设备名称弹出键盘时，页面上滑后输入框消失

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#447]
向上滑动页面，输入框消失
![image](https://user-images.githubusercontent.com/38175831/50809595-76e38380-133f-11e9-8468-3d31c4a07e3c.png)

**Comment by angel-developer** [comment]
iOS v1.1.0 (118) 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
