### ISSUE TITLE
温湿度解释页，表格整体请与上方文字左端对齐，并左右居中

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#454]
V65
![image](https://user-images.githubusercontent.com/38175831/50890391-0e76ce00-1435-11e9-9c4a-cfa38e962086.png)

**Comment by Dongwei0516** [comment]
Android v66 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51012836-392e6700-159a-11e9-8732-b8ef261d71fd.png)
表格整体右边偏右了，请居中
