### ISSUE TITLE
iOS，界面上的大标题文字，太细。评论中有图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#46]
如题。

<img width="988" alt="screen shot 2018-05-27 at 4 58 01 pm" src="https://user-images.githubusercontent.com/14070164/40584159-43966be0-61cf-11e8-8536-18fbcb45e2a6.png">

**Comment by GayoZhao** [comment]
建议直接用系统的字体。

**Comment by GuiYongZhao** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/37681560/40595759-3febe0d4-6269-11e8-94c8-4a7266c1c2e0.png">
建议参考音乐 app 的大标题。
