### ISSUE TITLE
iOS版app对tVOC故障的显示不对。Android也需要查一下。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#460]
![_20190111_202858 1](https://user-images.githubusercontent.com/14070164/51034899-3b68e380-15e3-11e9-8400-ff7049e899d0.jpg)

**Comment by dubinbeta** [comment]
用户在app里提交了反馈，留的号码是16621182281， @angel-developer

**Comment by jiaruirui323** [comment]
Android v121 验证未出现该情况
