### ISSUE TITLE
iOS，城市详情，降水概率显示异常

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#462]
![6f4559df-0352-4cd3-a3d1-815cbf9edd95](https://user-images.githubusercontent.com/14070164/51071746-f4d1c280-1690-11e9-8b03-c1707b421d82.jpg)
![0f23b031-40b2-461f-83d1-0f86a03fcc1f](https://user-images.githubusercontent.com/14070164/51071747-f69b8600-1690-11e9-8124-181f97a0a1b1.jpg)

**Comment by MiaomiaoCai** [comment]
V110验证未复现，服务器未采集到数据时，本地显示 “--”
