### ISSUE TITLE
设置，Widget，设备列表或城市列表，文字和按钮调整意见。详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#464]
在已选择的城市下方的现有说明文字后面增加（无需换行）：
简体：最多可显示 3 个城市。
繁體：最多可显示 3 個城市。
英文：Up to 3 cities can be displayed.
（注意：英文现有文字后面需要加一个空格，再跟上要增加的文字。）

**Comment by dubinbeta** [comment]
另外，请按照下图修改Widget内容管理界面：
![pasted_image_2019_2_11__8_53_pm](https://user-images.githubusercontent.com/14070164/52565052-b1f63c80-2e40-11e9-929b-9d9e9ed9a032.jpg)

简体：在小部件中可见
繁体：在小工具中可見
英文：VISIBLE IN WIDGET

简体：在小部件中不可见
繁体：在小工具中不可見
英文：HIDDEN IN WIDGET

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.  “添加按钮” 使用的是为系统按钮，不可置灰。

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64323002-346d6600-cff6-11e9-9218-cb2a42671dc2.png)
![image](https://user-images.githubusercontent.com/52393989/64322939-11db4d00-cff6-11e9-8887-17229117c54f.png)

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64323254-b52c6200-cff6-11e9-84f1-67f513e49e19.png)
