### ISSUE TITLE
主界面，城市卡片和设备卡片上的最后一行字符与卡片的下边缘的间距不相等，应相等。详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#468]
![wechatimg285](https://user-images.githubusercontent.com/14070164/51295623-6e7ffc80-1a53-11e9-9940-cf38f56ef7b6.jpg)

**Comment by angel-developer** [comment]
iOS v1.1.0 (109) 修复。

**Comment by MiaomiaoCai** [comment]
110验证已修复
