### ISSUE TITLE
snow详情页，点击温湿度读数，APP停止运行

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#475]
V 73

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/51663658-4fa0dd80-1ff2-11e9-9337-ab15768e893b.png)

**Comment by Dongwei0516** [comment]
Android V74 Fixed

**Comment by MiaomiaoCai** [comment]
V75验证已修复
