### ISSUE TITLE
请修改青萍空气app中的tVOC解读文字

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#479]
简体中文：

> tVOC 即总挥发性有机物，包含上千种化合物。室内人员增多，或进行烹饪、进餐、清洁、化妆等活动时， tVOC 读数可能大幅升高，通常会在相关活动结束或通风后回落。当检测仪附近有未密封的含酒精的物质或粘合剂、油漆时， tVOC  读数也会显著升高。室内 tVOC 还可能来自建筑和装饰、家具、家用电器使用的材料。
> 
> 当 tVOC 高于 3 mg/m³ 时，应避免在该环境下持续停留超过 1 个月。可开窗或打开新风换气设备通风、寻找并处理挥发源，以降低 tVOC 浓度。
> 
> 不同工作原理或不同厂商出品的检测设备的 tVOC 检测结果可能有较大差异。在不同环境下初始化的青萍空气检测仪的 tVOC 读数可能有较大差异。
> 
> 如要比较多台青萍空气检测仪的 tVOC 读数一致性，需在相同环境下同时重置他们的 tVOC 传感器，然后观察。

繁體中文：

> tVOC 即總揮發性有機物，包含上千種化合物。室內人員增多，或進行烹饪、進餐、清潔、化妝等活動時， tVOC 讀數可能大幅升高，通常會在相關活動結束或通風後回落。當檢測儀附近有未密封的含酒精的物質或粘合劑、油漆時， tVOC 讀數也會顯著升高。室內 tVOC 還可能來自建築和裝飾、家具、家用電器使用的材料。
> 
> 當 tVOC 讀數高于 3 mg/m³ 時，應避免在該環境下持續停留超過 1 個月。可開窗或打開新風換氣設備通風、尋找並處理揮發源，以降低 tVOC 濃度。
> 
> 不同工作原理或不同廠商出品的檢測設備的 tVOC 檢測結果可能有較大差異。在不同環境下初始化的青萍空氣檢測儀的 tVOC 讀數可能有較大差異。
> 
> 如要比較多台青萍空氣檢測儀的 tVOC 讀數一致性，需在相同環境下同時重置它們的 TVOC 傳感器，然後觀察。

英文：

> tVOC refers to total volatile organic compounds, containing thousands of compounds. When the number of people in the room increases, or when cooking, eating, cleaning, makeup, etc., tVOC readings may increase significantly, and usually decrease after the activities ends or ventilations have been done. The tVOC reading also increases significantly when there is an unsealed, alcohol-containing substance or adhesive or paint near the device. Indoor tVOC may also originates from materials used in construction and decoration, furniture and household appliances.
> 
> When tVOC is higher than 3 mg/m³, it should be avoided to stay in the environment for more than 1 month.
> 
> The tVOC readings from different sensors or devices produced by different manufacturers may vary greatly. The tVOC readings of ClearGrass Air monitor devices initialized in different environments may vary considerably.
> 
> To compare the tVOC readings of multiple ClearGrass Air Monitor devices, please reset their tVOC sensors in the same time and same environment and then observe.

注意：记得在切换单位后相关数字（3 mg/m³）和单位要变。

**Comment by angel-developer** [comment]
iOS v1.1.0 110 修复。

**Comment by MiaomiaoCai** [comment]
@angel-developer 110验证未修复
![image](https://user-images.githubusercontent.com/38175831/52706557-aa5da180-2fc0-11e9-98d0-a9b8166e8f4d.png)

**Comment by angel-developer** [comment]
iOS v1.1.0 111 修复。

**Comment by MiaomiaoCai** [comment]
iOS V111验证已修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
Android v77 验证已修复
