### ISSUE TITLE
设备详情，分享，对图片示意框的调整意见

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#48]
如题。

<img width="633" alt="screen shot 2018-05-27 at 6 12 09 pm" src="https://user-images.githubusercontent.com/14070164/40584769-990de40e-61d9-11e8-8559-7b18b10f631a.png">

**Comment by GuiYongZhao** [comment]
建议在下方放上 ClearGrass logo 及下载 app 的二维码。

**Comment by GuiYongZhao** [comment]
我认为这个分享页面，不应该只是简单的长截图，应该把整体布局优化一下，这个我周三前出需求。
