### ISSUE TITLE
分享城市详情的图片，行动建议文字距离上方的分割线过近

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#482]
![img_3281](https://user-images.githubusercontent.com/14070164/52565817-dfdc8080-2e42-11e9-9ac7-ba0ab1d60314.jpg)

**Comment by angel-developer** [comment]
iOS v1.1.0 111 修复。

**Comment by MiaomiaoCai** [comment]
iOS v143验证，最后一条行动建议与底部间距过小，请调整
![image](https://user-images.githubusercontent.com/38175831/57187604-35956600-6f24-11e9-8c21-00ad2312ece2.png)

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
1.英文时间日期，请参考iOS，应为9:00am 5/5
2.天气图标下面，应显示天气状况和温度，且使用灰色字体，小字号
3.UV和RH两行间距过大
4.最后一条行动建议与底部间距过小
![image](https://user-images.githubusercontent.com/38175831/57187624-755c4d80-6f24-11e9-87f6-7b850934b80b.png)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
iOS 144验证已修复

**Comment by jiaruirui323** [comment]
Android v120 验证未修复
1.天气图标下面，应显示天气状况和温度，且使用灰色字体，小字号
2.紫外线和花粉两行间距过大，缺少状况提示
3.最后一条行动建议与底部间距过小
![image](https://user-images.githubusercontent.com/52393989/64088466-27d9db00-cd74-11e9-9b50-b9618bd4cbdb.png)
