### ISSUE TITLE
修改温度单位为℉后，天气预报温度范围仍使用℃的值

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#486]
V110
![image](https://user-images.githubusercontent.com/38175831/53008754-07e86700-3475-11e9-973a-62ea72b88d67.png)
![image](https://user-images.githubusercontent.com/38175831/53008757-0c148480-3475-11e9-8fea-58ba9de3b014.png)

**Comment by angel-developer** [comment]
iOS v1.1.0 (112) 修复， 修改地方，城市卡片，城市详情， widget 定位城市， widget 城市列表

**Comment by MiaomiaoCai** [comment]
112验证，设置中，温度单位默认为℉，且无法切换为℃

**Comment by angel-developer** [comment]
iOS v1.1.0 (118) 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/53938173-4ecb9300-40ea-11e9-8189-a0702638275f.png)
@angel-developer ，切换单位为℉后，天气预报处仍使用℃

**Comment by angel-developer** [comment]
iOS  v1.1.0 （125） 修复。

**Comment by MiaomiaoCai** [comment]
126验证已修复
