### ISSUE TITLE
天气预报AQI范围，摘要处与柱状图处不一致，温度也存在此问题

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#487]
![image](https://user-images.githubusercontent.com/38175831/53156445-62f79680-35fa-11e9-8574-55fc23bebf78.png)
![image](https://user-images.githubusercontent.com/38175831/53156450-668b1d80-35fa-11e9-926b-14535c38a99c.png)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
iOS V144验证已修复

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64088748-80f63e80-cd75-11e9-94ea-6cfc536130b2.png)
