### ISSUE TITLE
城市详情，天气预报目前不支持侧滑返回，应支持。

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#488]
如题。

**Comment by angel-developer** [comment]
iOS v1.1.0 (112) 修复。

**Comment by MiaomiaoCai** [comment]
116验证
1.天气预报24小时tab处，侧滑再取消，会跳到15天tab
2.天气预报15天tab处，滑动到列表末尾处，侧滑再取消，会闪动到列表开端处
3.AQI预报也存在这两个问题，请一同优化

**Comment by angel-developer** [comment]
iOS v1.1.0 (118) 修复，修改地方：城市详情， Snow 详情。

**Comment by MiaomiaoCai** [comment]
118验证未修复

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
