### ISSUE TITLE
未添加过城市和设备，设置处开启早晚空气质量，未弹出通知权限的申请

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#490]
V111
安装app后首次启动
![image](https://user-images.githubusercontent.com/38175831/53473045-5b296d80-3aa4-11e9-908e-7677bddb8229.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证已修复
