### ISSUE TITLE
获取通知权限后，开启早晚空气质量通知提示“Setting Error1000”

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#491]
![image](https://user-images.githubusercontent.com/38175831/53477942-b95c4d80-3ab0-11e9-976b-cc56216e2af0.png)

**Comment by MiaomiaoCai** [comment]
V111

**Comment by angel-developer** [comment]
iOS  v1.1.0 (118) 修复。

**Comment by MiaomiaoCai** [comment]
122验证，获取通知权限后，此处也会被开启
