### ISSUE TITLE
iOS，设备详情，设备管理，检查更新，提示“The current version is the latest”句末缺英文句号“.”

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#492]
如题。

**Comment by angel-developer** [comment]
iOS  v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58308945-7272bf80-7e35-11e9-9306-c5e3e4614205.png)
iOS V144验证已修复

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64509446-4d398c80-d312-11e9-9bdf-0c6f58c8f590.png)
