### ISSUE TITLE
Android，主界面，卡片上显示的建议措施，“建议措施”小标题和下方的多条措施文字之间的间距不均匀，请参考iOS修改。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#496]
如题。

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54348448-03822900-4684-11e9-93fc-c4c18f391df1.png)
验证已修复
