### ISSUE TITLE
分享设备或城市的读数的界面，选单和待分享的图片的背景颜色，不应一致，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#497]
1和2的颜色不应一致：
![img_6cde7d32f101-1](https://user-images.githubusercontent.com/14070164/53710891-5a188780-3e7a-11e9-8b0d-7d517983b290.jpg)

**Comment by angel-developer** [comment]
iOS v1.1.0 (118) 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54099947-d40abc80-43f6-11e9-9d54-700d3d49c37b.png)
iOS V122验证已修复

**Comment by Dongwei0516** [comment]
Android v91 更新设计。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58074540-19f2b680-7bd8-11e9-8deb-824471df7da0.png)
Android v94，背景需改为透明
