### ISSUE TITLE
Android，toast提示条的背景颜色太浅（或透明度太高），请把背景颜色调深一点，以便更容易阅读提示文字。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#499]
如题。

**Comment by Dongwei0516** [comment]
Android v77解决，透明度降低

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54263348-9b601400-45ab-11e9-9b68-3c6d9330fe65.png)
@Dongwei0516 toast背景请与弹窗背景统一

**Comment by MiaomiaoCai** [comment]
78验证已修复
![image](https://user-images.githubusercontent.com/38175831/54408666-a76be300-471d-11e9-963b-fcf803b9ef96.png)
