### ISSUE TITLE
添加Goose自定义名称，默认为“青萍空气检测仪”

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#512]
V124，手机系统语言为中文时
![image](https://user-images.githubusercontent.com/38175831/54342959-aa60c800-4678-11e9-878e-69943d56d0db.png)

**Comment by angel-developer** [comment]
iOS  v1.1.0 (125）修复。

**Comment by MiaomiaoCai** [comment]
126验证已修复
