### ISSUE TITLE
温度单位切换成℉后，天气预报仍使用℃

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#513]
![image](https://user-images.githubusercontent.com/38175831/54343798-8aca9f00-467a-11e9-9030-c9f52ef9fc12.png)

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64100097-718aeb80-cd9d-11e9-9794-fa26e4cd0fc3.png)
