### ISSUE TITLE
设备名称输入框，输入字符后，请添加清空按钮

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#514]
V77
![image](https://user-images.githubusercontent.com/38175831/54348919-1c3f0e80-4685-11e9-9c0e-776920cc7d11.png)

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
Android v94，字符为空时，不需要显示清空按钮
![image](https://user-images.githubusercontent.com/38175831/57595470-c9e07800-7577-11e9-904d-f9e0cbe51d94.png)

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V100验证已修复
