### ISSUE TITLE
添加设备成功命名页面，请去掉左上角的叉号，只保留跳过按钮

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#517]
V78

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/57595138-fb584400-7575-11e9-87bb-5186ce6643d9.png)
Android V94，验证未修复

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/59180044-73765180-8b96-11e9-81d8-ce1e7a98e4c0.png)
验证已修复
