### ISSUE TITLE
Android，发现新版，点击更新，弹框里的文字中的版本号，请用双引号，中文下用中文的，英文下用英文的（注意：英文标点前面和后面需要加空格）。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#521]
![61552896036_ pic_hd](https://user-images.githubusercontent.com/14070164/54515428-012b1200-4997-11e9-9953-b5e052bc46bd.jpg)

**Comment by dubinbeta** [comment]
中文：发现新版”x.xxx“，是否更新？
繁体：發現新版“x.xxx”，是否更新？
英文：New version "x.xxx" found, update now?

**Comment by Dongwei0516** [comment]
Android v79 修复。

**Comment by MiaomiaoCai** [comment]
Android V81验证已修复
![image](https://user-images.githubusercontent.com/38175831/55871514-5edd0380-5bbd-11e9-9310-9d41d7b4d7ee.png)
