### ISSUE TITLE
Android，“建议措施”这几个字与下方元素的间距过小，请参照iOS的做修改。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#525]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/14070164/54520560-f034cd80-49a3-11e9-96be-624c568e3f70.png">

**Comment by MiaomiaoCai** [comment]
Android v91，iOS v143，此处的UI都需要调整，贝贝会提供新的设计图
![image](https://user-images.githubusercontent.com/38175831/56947707-8d1c8600-6b60-11e9-877c-f632a1c28c0a.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
