### ISSUE TITLE
主界面卡片、Widgets里的读数评价文字与右侧其他读数的小圆点之间的间距问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#526]
<img width="966" alt="Screen Shot 2019-03-19 at 3 10 41 PM" src="https://user-images.githubusercontent.com/14070164/54586831-2f712600-4a59-11e9-9b0e-880a80f84044.png">

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58446027-a863bc80-8131-11e9-94de-142e392bbd41.png)
验证已修复
