### ISSUE TITLE
提交反馈，提交失败时的错误提示文字不合适，需修改，详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#527]
![b5b6b280-d99d-4f19-acbb-839599847a84](https://user-images.githubusercontent.com/14070164/54595272-402b9700-4a6d-11e9-8bf8-7e2a02188b0b.jpg)

Disconnect请改为：Submission failed
中文：提交失败
繁体：提交失敗

**Comment by angel-developer** [comment]
iOS  v126 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/55372901-e085bf00-5535-11e9-95f2-0f80cf72f9b7.png)
验证已修复
