### ISSUE TITLE
请统一app中出现的英文产品名称

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#530]
1. 添加产品的列表：
* ClearGrass Temp & RH Monitor
* ClearGrass Air Monitor
* ClearGrass Temp & RH Barometer
注：添加产品过程中，界面上显示的产品名称同上。App中其他所有需要完整产品名称的地方也同上。

2. 在命名产品时跳过的话，自动给产品的默认名称：
* Temp & RH Monitor
* Air Monitor
* Temp & RH Barometer

**Comment by angel-developer** [comment]
iOS v126 修复。 修改地方： 首页产品列表，添加设备（Snow、Goose、Pheasant） 子标题。
添加设备时的默认名。修改名字时的默认值。 添加（Goose、 Pheasant) 设备的提示语（按压2s）。

**Comment by MiaomiaoCai** [comment]
验证已修复
