### ISSUE TITLE
Android，已使用Facebook登录，设置中不应显示”Logged in with WeChat“，应显示为”Logged in with Facebook“；另，登出确认对话框上的文字Logged in with Facebook"xxxx"应为Logged in with Facebook "xxxx"

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#531]
如题。

**Comment by Dongwei0516** [comment]
Android v79 修复。

**Comment by MiaomiaoCai** [comment]
Android V91验证，此处需要添加空格
![image](https://user-images.githubusercontent.com/38175831/57186965-7b4d3100-6f1a-11e9-9716-553052d54e82.png)

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v121 验证修复
![image](https://user-images.githubusercontent.com/52393989/64607115-6cabe480-d3fa-11e9-83e8-126d714ec730.png)
