### ISSUE TITLE
添加完设备，为设备选择名称的界面，待选的名称文字不应进入按钮左右侧半圆区域。可重新设计此界面，以达到显示更多字符的目的，要兼容换行。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#533]
![IMG_3540](https://user-images.githubusercontent.com/14070164/54603555-9570a400-4a7f-11e9-806b-7fee8ba1b2d2.jpg)

**Comment by beibeixiao666** [comment]
设计已调整，发给了技术

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证已修复
