### ISSUE TITLE
Android，主界面，”显示当前城市的空气质量“条目上的元素，对齐无依据，请根据设计稿修改。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#539]
![Pasted_Image_2019_3_19__10_49_PM](https://user-images.githubusercontent.com/14070164/54615706-872f8180-4a99-11e9-8937-729df3ff17b5.jpg)

**Comment by Dongwei0516** [comment]
Android v121 修复。

**Comment by jiaruirui323** [comment]
Android v121 未修复
![image](https://user-images.githubusercontent.com/52393989/64501645-c5915500-d2f4-11e9-9b5a-d6c5a8ec16e5.png)
