### ISSUE TITLE
Android，用户未设置名称的设备，应按照默认名称命名，不应是空的。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#540]
![Pasted_Image_2019_3_19__10_49_PM](https://user-images.githubusercontent.com/14070164/54616084-1f2d6b00-4a9a-11e9-80ba-48223b5143ee.jpg)

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V100验证已修复
