### ISSUE TITLE
iOS，手机蓝牙关闭后进入Goose详情页，提示打开蓝牙的英文提示文字，需要修改，详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#541]
现在是：Bluetooth is off, please turn on Bluetooth to connect device.
请改为：Bluetooth is off, please turn on to connect the device.

**Comment by dubinbeta** [comment]
现在是：Bluetooth is off, please turn on Bluetooth to connect device.
请改为：Bluetooth is off, please turn on to connect the device.

**Comment by angel-developer** [comment]
iOS v126 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
