### ISSUE TITLE
分享Pheasant给家人或朋友时，分享出去的链接名称、打开的网页上的设备名称和设备图标错误。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#544]
如题。

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58447684-c92f1080-8137-11e9-976b-6dc9b06b472c.png)
![image](https://user-images.githubusercontent.com/38175831/58447698-cfbd8800-8137-11e9-88e7-4933107b22ee.png)
验证已修复
