### ISSUE TITLE
Pheasant管理界面，管理上报时间间隔和数据粒度等的滚轴控件的样式问题，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#549]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/14070164/54678338-e47e0e00-4b3f-11e9-8669-7df6f044aa21.png">

**Comment by beibeixiao666** [comment]
![主页面3 1](https://user-images.githubusercontent.com/39484901/55143350-87a2d900-5179-11e9-9608-845ea667a5f1.png)设计已修改，已发技术修改

**Comment by beibeixiao666** [comment]
设计已修改，已发技术修改
![主页面3 1](https://user-images.githubusercontent.com/39484901/55147411-4d3d3a00-5181-11e9-8cff-7c48476df008.png)

**Comment by angel-developer** [comment]
iOS v1.1.0 139 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58159086-5d1f5900-7cae-11e9-9eee-93b579c59322.png)
iOS v144验证已修复
