### ISSUE TITLE
点击“登录”，应询问用户是否同意使用微信登录。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#55]
如题。

**Comment by dubiao** [comment]
产品上改成了点登陆后会显示出来跳到微信登陆的上滑出来的菜单图标
![image](https://user-images.githubusercontent.com/4001793/40638161-202671dc-633c-11e8-8030-97258aa9ecf2.png)

**Comment by GuiYongZhao** [comment]
讨论后，决定“登录” button 文字改为“微信登录”。
