### ISSUE TITLE
Pheasant管理界面, 编辑触发上报和通知的条件界面的UI修改意见，详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#550]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14070164/54678406-0f686200-4b40-11e9-92f0-57ff47414a48.png">

**Comment by beibeixiao666** [comment]
UI 已发给Android和ios调整
![4 5](https://user-images.githubusercontent.com/39484901/55137160-34c22500-516b-11e9-9fbd-1129583c5aee.png)

**Comment by angel-developer** [comment]
iOS v137 修复。

**Comment by Dongwei0516** [comment]
Android v80 修复。

**Comment by Dongwei0516** [comment]
Android v80 修复。

**Comment by MiaomiaoCai** [comment]
iOS 138验证已修复
![image](https://user-images.githubusercontent.com/38175831/55374562-77a14580-553b-11e9-9520-7fcdd551fffc.png)

**Comment by MiaomiaoCai** [comment]
Android v81验证已修复
