### ISSUE TITLE
Pheasant管理界面，“条件触发通知”界面默认应为空，目前是默认有一条。缺个为空的界面。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#551]
如题。

**Comment by angel-developer** [comment]
iOS v144 解决。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58448289-f67cbe00-8139-11e9-9ecc-f1f9b072f9cf.png)
iOS V144验证已修复

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64099850-deea4c80-cd9c-11e9-9987-0e7f7dadfdaa.png)
