### ISSUE TITLE
Pheasant和Goose的固件更新过程中，页面上显示的红色文字“Do not leave this page”请改为黑色（中文也是）。另，英文需要加上英文句号。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#556]

**Comment by angel-developer** [comment]
iOS v139 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58232247-a681ae00-7d6b-11e9-975d-976a07a1046e.png)
![image](https://user-images.githubusercontent.com/38175831/58232744-e8f7ba80-7d6c-11e9-9d80-a93ae02ffbb2.png)
iOS V144验证已修复
