### ISSUE TITLE
Goose和Pheasant，通过蓝牙更新固件，正在更新时，点击界面左上角的返回，弹出的提示框，文字需要修改

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#557]
英文请改为：Go back now will cancel the update, are you sure you want to go back?
按钮1：No
按钮2：Yes

中文请改为：现在返回将取消更新，您确认要返回吗？
按钮1：否
按钮2：是

繁體：現在反悔將取消更新，您確認要返回嗎？
按鈕1: 否
按鈕2: 是

**Comment by angel-developer** [comment]
iOS  v139 修复。

**Comment by MiaomiaoCai** [comment]
iOS V143验证，未使用No and Yes
![image](https://user-images.githubusercontent.com/38175831/56886233-19677400-6aa1-11e9-8a33-9064cda1ba9f.png)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58320200-b8d41880-7e4d-11e9-8db0-8516321aea2c.png)
iOS V144验证已修复
