### ISSUE TITLE
Pheasant固件更新界面上的图标、文字是Goose的，不应如此。（英文的是这样，中文我还没看。）

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#558]
如题。

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
iOS V143验证已修复
![image](https://user-images.githubusercontent.com/38175831/56883701-0ac98e80-6a9a-11e9-8d35-94079efa3e00.png)
Android V91验证已修复，为适配多种机型不同屏幕，产品名称处设置了一个最大长度，超过这个长度会换行
![image](https://user-images.githubusercontent.com/38175831/56883763-3a789680-6a9a-11e9-9022-2c120ca2abeb.png)
