### ISSUE TITLE
iOS Widgets里的蓝牙图标，和app主界面里的卡片上的以及设备详情界面里的蓝牙图标，样式不统一，应统一。另外，目前的都不好看，请参考评论附图修改。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#561]
![iconfinder_bluetooth-b_1608579](https://user-images.githubusercontent.com/14070164/54900230-676ee200-4f0d-11e9-80c1-3c834d191c67.png)

Android版也要照此更新。

解释一下：
* 现在iOS主界面卡片上的和设备详情里的蓝牙图标，比例不协调，左侧过大。
* 现在iOS Widgets里面的蓝牙图标，末端是圆的，线条略粗，和Android和iOS里的常见字体（末端不圆润）有违和感。

**Comment by yezhinan** [comment]
IOS 及 android 已替换完毕

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证已修复
