### ISSUE TITLE
Android，添加城市，定位失败，提示语“Positioning fail”请改为“Failed to get location”

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#564]
如题。

![Screenshot_20190325-192641](https://user-images.githubusercontent.com/14070164/54971835-60a2a680-4fc3-11e9-8781-5c5d558bcc81.png)

**Comment by dubinbeta** [comment]
如题。

![Screenshot_20190325-192641](https://user-images.githubusercontent.com/14070164/54971835-60a2a680-4fc3-11e9-8781-5c5d558bcc81.png)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证 未开定位服务提示正确
![image](https://user-images.githubusercontent.com/52393989/64094724-34b7f800-cd8f-11e9-89be-c9a896240bec.png)

**Comment by jiaruirui323** [comment]
Android v120
没有开启当前城市，未开定位服务，点击定位城市没有反应，会闪退崩溃

**Comment by jiaruirui323** [comment]
出现其他问题已转到TAPD
