### ISSUE TITLE
Android, 添加城市，当前定位城市，按钮上的图标和文字之间间距过大

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#565]
![Screenshot__Mar_26__2019_12_34_35_PM_](https://user-images.githubusercontent.com/14070164/54972004-6baa0680-4fc4-11e9-9b03-8f342b7d5790.jpg)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56861504-076bcf80-69d4-11e9-85aa-3087c90bf0b9.png)
请使用新设计
