### ISSUE TITLE
添加城市，城市待选界面，推荐选择的城市们的圆角矩形按钮，目前是等宽的，请改为宽度自适应的（当然，要指定最小宽度和最大宽度、要做好换行）。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#566]
优先级不高。对于支持国外的城市有意义。

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58246542-ef485f80-7d89-11e9-8ec9-66993d6a4573.png)
iOS V144，需要调整
