### ISSUE TITLE
修改已有条件失败

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#569]
iOS V126
1.修改已有条件-选择AP-1000kPa-保存
2.退出返回查看此条件-单位变成温度
![image](https://user-images.githubusercontent.com/38175831/54972384-4b7b4700-4fc6-11e9-84a3-37f33692e9cf.png)

**Comment by angel-developer** [comment]
iOS v137 修复。

**Comment by MiaomiaoCai** [comment]
138验证已修复
