### ISSUE TITLE
英文状态下，导出的历史数据文件，文件名中没有设备名称，文件打开后也看不到设备名称。

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#572]
![Pasted_Image_2019_4_11__4_49_PM](https://user-images.githubusercontent.com/14070164/55944387-16841b00-5c7b-11e9-831d-80925ffa0436.jpg)

![Pasted_Image_2019_4_11__5_00_PM](https://user-images.githubusercontent.com/14070164/55944517-5a772000-5c7b-11e9-943c-28d5f352bf92.jpg)

**Comment by server-go** [comment]
已修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58614837-1bb12e00-82ec-11e9-905f-595ccfe16e9e.png)
验证已修复
