### ISSUE TITLE
添加Pheasant Wi-Fi版，连接Wi-Fi的界面，Wi-Fi名称文字和密码输入框内的字符，左起位置都不应是屏幕最左侧，应留出间距；输入Wi-Fi密码时，应调起密码键盘。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#575]
如题。

**Comment by angel-developer** [comment]
iOS v137 修复。

**Comment by MiaomiaoCai** [comment]
iOS V143验证已修复
![image](https://user-images.githubusercontent.com/38175831/56939663-34d38d00-6b3c-11e9-9cbd-698f04ecb5df.png)
![image](https://user-images.githubusercontent.com/38175831/56939669-39984100-6b3c-11e9-80ce-5035830f62c4.png)

**Comment by MiaomiaoCai** [comment]
Android V100验证已修复
