### ISSUE TITLE
pheasant温度读数是零下时，App卡片读数显示异常

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#577]
iOS V126
![image](https://user-images.githubusercontent.com/38175831/54991230-77fb8700-4ff7-11e9-925a-2ff104def36d.png)
![image](https://user-images.githubusercontent.com/38175831/54991246-7d58d180-4ff7-11e9-98a4-0c6f8625a7cb.png)

**Comment by angel-developer** [comment]
iOS  v137 修复。

**Comment by MiaomiaoCai** [comment]
138验证已修复
![image](https://user-images.githubusercontent.com/38175831/55302810-7f96b200-5475-11e9-9b98-321896b97fad.png)
