### ISSUE TITLE
温度零下时的历史数据UI需调整

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#578]
iOS V127
![image](https://user-images.githubusercontent.com/38175831/55136618-e2343900-5169-11e9-9057-3e594ee85dc8.png)

**Comment by angel-developer** [comment]
iOS v137 修复。

**Comment by MiaomiaoCai** [comment]
138验证已修复

![image](https://user-images.githubusercontent.com/38175831/55308008-ed4dd880-548b-11e9-8ce7-b6b736136fdc.png)
