### ISSUE TITLE
从设备详情进入的设备管理界面，应能显示设备的序列号或MAC

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#579]
如题。

最好是只显示序列号，因为有的设备会有好几种MAC地址（例如Pheasant）。需要能通过序列号反查MAC。

如果没有序列号且只有一种MAC（例如Goose），则显示MAC地址。

优先级：中等。

**Comment by angel-developer** [comment]
iOS  v140 修复，显示设备序列号。

**Comment by Dongwei0516** [comment]
Android v85 修复，显示设备序列号。

**Comment by MiaomiaoCai** [comment]
iOS V143验证已修复，Android V91验证已修复

**Comment by MiaomiaoCai** [comment]
目前iOS v143，Android v91验证，pheasant设备管理页会显示序列号，但是Snow，Goose也需要实现此需求

**Comment by angel-developer** [comment]
iOS v144 修复。Snow 和 Goose 显示 MAC

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58533926-68c5cf00-821c-11e9-950e-0a9712d87b28.png)
![image](https://user-images.githubusercontent.com/38175831/58533935-711e0a00-821c-11e9-9ce7-6a02ebe04f02.png)
iOS 144验证未修复

**Comment by angel-developer** [comment]
内测版 iOS v170 修复。

**Comment by jiaruirui323** [comment]
iOS 149 验证修复
![IMG_0063](https://user-images.githubusercontent.com/52393989/62364602-85e88800-b554-11e9-890b-83e6c8db0d93.PNG)
