### ISSUE TITLE
请去掉夜间的天气图标中的白色星星，会让人觉得是雪花（黄色的星星不用去掉）。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#580]
相应地，Snow OS也需要改。

![IMG_3612](https://user-images.githubusercontent.com/14070164/55286579-098c3f80-53d0-11e9-99b4-c8b4b1853536.jpg)

**Comment by dubinbeta** [comment]
优先级低。

**Comment by beibeixiao666** [comment]
已修改图标发送给技术

**Comment by angel-developer** [comment]
iOS v140 修复。

**Comment by Dongwei0516** [comment]
Android v82 修复。

**Comment by MiaomiaoCai** [comment]
Android V87验证已修复
![image](https://user-images.githubusercontent.com/38175831/56648512-11c95900-66b6-11e9-965e-6d1254fd7a65.png)

**Comment by MiaomiaoCai** [comment]
iOS V143验证未修复
![image](https://user-images.githubusercontent.com/38175831/56648559-2574bf80-66b6-11e9-97bb-a0dbefd4ebac.png)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58534441-ec33f000-821d-11e9-8141-ef5273d526ac.png)
iOS V144验证已修复
