### ISSUE TITLE
Pheasant温度零下时，读数解释页显示--

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#581]
![image](https://user-images.githubusercontent.com/38175831/55302852-c4224d80-5475-11e9-95e9-32b1d4e7d149.png)
iOS V138

**Comment by angel-developer** [comment]
iOS v139 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56878969-35f7b200-6a89-11e9-99dd-ebd4fea6481b.png)
iOS V143验证已修复
