### ISSUE TITLE
请在主界面卡片上、Widget里、设备详情界面，用图标体现Pheasant和Goose的产品类型

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#582]
请在下图中红圈所圈出的位置用图标体现Pheasant的类型，即“NB-IoT”、“LoRa”、“Wi-Fi”：

1. 主界面的卡片和Widgets上：
![Pasted_Image_2019_4_1__12_43_PM](https://user-images.githubusercontent.com/14070164/55304090-575e8180-547c-11e9-8a0d-bdb0964d9625.jpg)

2. 设备详情界面上（向上滚动后随着大字变成小字，图标也消失）：
![IMG_3636](https://user-images.githubusercontent.com/14070164/55304173-c6d47100-547c-11e9-8f6d-0ef5666fd7ee.jpg)

另外，HomeKit版Goose也要用类似方法体现。

**Comment by angel-developer** [comment]
iOS  v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58540223-85b5ce80-822b-11e9-99ad-d9f37fdebebd.png)
iOS V144验证已修复

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64099045-ec9ed280-cd9a-11e9-9b6e-b63dfc69b0c9.png)

**Comment by jiaruirui323** [comment]
Android v120 设备详情页没有图标体现区别
