### ISSUE TITLE
切换美国标准后，首页城市卡片AQI的预报范围是中国标准下的范围

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#586]
Android v 79
![image](https://user-images.githubusercontent.com/38175831/55528071-29707b80-56ce-11e9-9ec2-c63c77264c98.png)

**Comment by Dongwei0516** [comment]
Android v81 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
