### ISSUE TITLE
pheasant，添加设备页面，请使用“温湿度气压计”

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#589]
iOS V139
![image](https://user-images.githubusercontent.com/38175831/55709738-8b591a00-5a1b-11e9-882c-7750839e8267.png)

**Comment by angel-developer** [comment]
iOS v140 修复。

**Comment by MiaomiaoCai** [comment]
Android V81也存在此问题

**Comment by Dongwei0516** [comment]
Android v82 修复。

**Comment by MiaomiaoCai** [comment]
Android V91，iOS V143验证已修复
