### ISSUE TITLE
Android，当有新版时，主界面右上角的红点，不好看，需要设计一下。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#590]
如题。已跟 @beibeixiao666 @yezhinan 沟通。

**Comment by beibeixiao666** [comment]
![主页面4 1](https://user-images.githubusercontent.com/39484901/55866519-1a4c6a80-5bb3-11e9-9a8d-ae88a96fd890.png)
设计已调整，发给了安卓

**Comment by Dongwei0516** [comment]
Android v86 更新设计图。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56860711-2ebe9e80-69cc-11e9-9cbe-e5b5a60ab04e.png)
验证已修复
