### ISSUE TITLE
VPN未打开，Facebook登录超时的提示需优化

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#591]
Android V81
请提示“登录超时”
![image](https://user-images.githubusercontent.com/38175831/55862160-79f24800-5baa-11e9-8fa7-bb74f9876575.png)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56860923-5f9fd300-69ce-11e9-8af1-9907c4a1019b.png)
V91验证已修复
