### ISSUE TITLE
导出历史数据，输入邮箱地址提交后的成功提示，文字需要修改。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#592]
中文：历史数据文件将在 5 分钟内发送到您填写的邮箱。
繁體：歷史數據文件將在 5 分鐘內發送到您填寫的郵箱。
英文：The historical data file will be sent via email in 5 minutes.

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
Android v91验证已修复

**Comment by MiaomiaoCai** [comment]
https://github.com/ClearGrass/Air-App-Issues/issues/346，@董威，Android V91验证，成功提示目前用toast弹出，请使用页面

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by Dongwei0516** [comment]
Android v95 成功提示修改为页面。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58456659-5170de00-8157-11e9-996c-8e6653f6ced8.png)
iOS V144验证已修复

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58456755-9bf25a80-8157-11e9-83d9-28e47e7c1373.png)
Android V95验证已修复
