### ISSUE TITLE
主界面卡片上的蓝牙图标、详情界面的蓝牙图标，大小不一致。应一样小。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#595]
如下图：卡片上的大一些，应该和详情界面一样小。
<img width="803" alt="Screen Shot 2019-04-13 at 6 35 17 PM" src="https://user-images.githubusercontent.com/14070164/56078478-14f15900-5e1b-11e9-98c6-256408d745f0.png">

**Comment by MiaomiaoCai** [comment]
https://github.com/ClearGrass/Air-App-Issues/issues/599
