### ISSUE TITLE
Pheasant的详情界面，点击“i”图标看到的连接说明界面，文字修改意见。详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#596]
![IMG_3694](https://user-images.githubusercontent.com/14070164/56105676-06688600-5f70-11e9-9797-71fab9912a22.jpg)

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
iOS V144验证未修复

**Comment by angel-developer** [comment]
iOS v146 修复。

**Comment by angel-developer** [comment]
iOS v146 修复。

**Comment by jiaruirui323** [comment]
iOS  147验证未修复
![QQ截图20190712105515](https://user-images.githubusercontent.com/52393989/61098992-79ac6600-a493-11e9-9afd-21d0bea4421d.png)

**Comment by angel-developer** [comment]
内测版 iOS v170 修复。

**Comment by jiaruirui323** [comment]
iOS v149 验证已修复
![IMG_0060](https://user-images.githubusercontent.com/52393989/62349485-78baa180-b532-11e9-85d4-6a035294463a.PNG)
