### ISSUE TITLE
Pheasant设备详情，管理，“数据上传和通知”，“条件触发通知”，界面为空时，应有文字说明。详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#597]
如题。文字颜色应为灰色。三种语言的文字分别为：
![IMG_3692](https://user-images.githubusercontent.com/14070164/56105755-7ecf4700-5f70-11e9-899b-29556776969c.jpg)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
Android V85验证已修复

**Comment by beibeixiao666** [comment]
![384d4683-45d6-48fc-b11d-0a1925caa3b2](https://user-images.githubusercontent.com/39484901/56270560-0069d500-6129-11e9-870d-cdcdae8f6eb1.jpg)
已发给技术处理

**Comment by MiaomiaoCai** [comment]
@angel-developer 繁体和英文状态仍使用简体中文

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58460349-0b6c4800-8160-11e9-98b2-43b3bc69d78a.png)
iOS V144验证已修复

**Comment by jiaruirui323** [comment]
Android v120 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64088117-8dc56300-cd72-11e9-9103-5932e5628413.png)
