### ISSUE TITLE
Android，主界面卡片和设备详情界面的蓝牙图标，需要更新，请参考iOS的。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#599]
如题。
![WechatIMG24](https://user-images.githubusercontent.com/14070164/56107137-251e4b00-5f77-11e9-99a3-df7c82e7d4fa.png)

**Comment by Dongwei0516** [comment]
Android v85 已修复。

**Comment by MiaomiaoCai** [comment]
Android V91，Goose详情页，蓝牙图标未使用最新的图标

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56860415-01242600-69c9-11e9-8c95-cb74995ffa65.png)

**Comment by Dongwei0516** [comment]
Android v92 Goose/Pheasant 卡片详情页蓝牙图标已更新。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/57594892-d0b9bb80-7574-11e9-990c-12a8d078257f.png)
Android v94验证已修复
