### ISSUE TITLE
Android，Pheasant，无法通过蓝牙更新固件。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#600]
如题。按钮灰色显示：
![WechatIMG25](https://user-images.githubusercontent.com/14070164/56107377-7aa72780-5f78-11e9-8fa4-8f43f5157c52.png)

**Comment by Dongwei0516** [comment]
Android v86 更新页面设计。

**Comment by MiaomiaoCai** [comment]
Android v91验证已修复
![image](https://user-images.githubusercontent.com/38175831/56860697-fe770000-69cb-11e9-9f95-49ab7e2ab2bc.png)
