### ISSUE TITLE
Android，Pheasant，数据上报和通知，提示更新生效时间的文字，需要稍作修改。详见附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#601]
![WechatIMG26](https://user-images.githubusercontent.com/14070164/56107450-e12c4580-5f78-11e9-948f-205b3d40ce64.jpg)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
v91验证已修复
