### ISSUE TITLE
Android，数据上报和通知，条件触发上报界面为空时，界面上的说明文字不应为红色。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#602]
如题。参见 #597 。
![WechatIMG27](https://user-images.githubusercontent.com/14070164/56107474-13d63e00-5f79-11e9-9397-42a4dda1f6d3.png)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56193820-1cf00980-6064-11e9-8ea8-8f3fb280039d.png)
验证已修复
