### ISSUE TITLE
Android，Pheasant连接说明界面，文字修改意见，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#604]
![WechatIMG28](https://user-images.githubusercontent.com/14070164/56108389-3cad0200-5f7e-11e9-8a81-c66e1ab121b4.jpg)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56858666-949d2d00-69b0-11e9-9a60-baeab5d535da.png)
Android v90，这两句与上文重复
