### ISSUE TITLE
PM2.5解读界面，文字“PM2.5 即是...”请改为“PM2.5 即...”

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#605]
Android是这样，iOS我没看，如果iOS也是，也请改掉。
![Pasted_Image_2019_4_16__3_45_PM](https://user-images.githubusercontent.com/14070164/56191300-b1f00400-605e-11e9-8d5a-b8dfc953cc21.jpg)

**Comment by Dongwei0516** [comment]
Android v85 修复。

**Comment by MiaomiaoCai** [comment]
Android V90验证已修复，包括snow和城市详情页，iOS V143验证无此问题
