### ISSUE TITLE
城市详情页，点击AQI读数未进入详情页

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#606]
Android V85
另请去掉AQI读数旁边的标准切换入口，换成AQI范围，参考iOS
![image](https://user-images.githubusercontent.com/38175831/56199379-66922180-606f-11e9-8f10-a598a221687f.png)

**Comment by Dongwei0516** [comment]
Android v86 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56858183-9236d500-69a8-11e9-95eb-204755427bbe.png)
请扩大AQI点击范围

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V98验证已修复
