### ISSUE TITLE
iOS，widget里的Goose等蓝牙设备，在当前未连接时，也应灰色显示，目前没有。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#607]
![IMG_3703](https://user-images.githubusercontent.com/14070164/56334246-25faeb00-61ca-11e9-8916-0a63ef399350.jpg)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64331826-16a7fd00-d006-11e9-837c-8ec82175579f.png)
