### ISSUE TITLE
pheasant，主人端修改设备名称后，共享给客人端的设备名称未更新

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#608]
iOS v142

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56411681-27a0dd80-62b4-11e9-933c-d7e35b7ef6b0.png)
在编辑页面请显示 来自“XX“

**Comment by angel-developer** [comment]
iOS v144 修复。

**Comment by MiaomiaoCai** [comment]
V145验证，客户端未更新名称

**Comment by angel-developer** [comment]
iOS v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 验证修复
