### ISSUE TITLE
分享读数详情或发送共享设备的邀请失败时的提示语应作区分，目前用的是一样的。详见评论。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#61]
- 分享读数失败：分享未成功
- 分享读数成功：已分享
- 用户主动取消分享时，不需要显示提示。

---------

- 共享设备邀请发送失败：共享邀请未发送
- 共享设备邀请发送成功：共享邀请已发送
- 用户主动取消发送共享邀请时，不需要显示提示。

**Comment by MiaomiaoCai** [comment]
@angel-developer iOS V111验证未看到相关提示

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
https://github.com/ClearGrass/Air-App-Issues/issues/200，需求已更新
