### ISSUE TITLE
AQI预告通知里的AQI最高值和最低值之间的分隔符号，请从“-”改为“~”。评论有附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#611]
![IMG_3738](https://user-images.githubusercontent.com/14070164/56745988-52a89700-67b6-11e9-8318-bf4d55661524.jpg)

**Comment by server-go** [comment]
已修复，请查验！

**Comment by MiaomiaoCai** [comment]
验证已修复
