### ISSUE TITLE
城市分享图片，当该城市不限行时，限行车牌未正常显示文字“无”

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#614]
如题。

**Comment by Dongwei0516** [comment]
Android v91 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56874367-156d2f00-6a6c-11e9-9129-c7124e30ffec.png)
验证已修复
