### ISSUE TITLE
繁体中文时，添加条件气压选项显示为“歷史”

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#615]
iOS v143

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/56861278-f6ba5a00-69d1-11e9-89c4-5a40cb3530b6.png)

**Comment by angel-developer** [comment]
iOS  v144 修复。

**Comment by MiaomiaoCai** [comment]
验证修复
