### ISSUE TITLE
城市详情页，天气图标处请显示天气状况和气温范围

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#616]
Android V91，请与iOS一致
![image](https://user-images.githubusercontent.com/38175831/56875323-b828ac00-6a72-11e9-9a07-bb5a57270eb6.png)

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/57594570-5472a880-7573-11e9-9da3-572ea828a90b.png)
Android V94验证已修复
