### ISSUE TITLE
未使用当前城市卡片时，每次进入添加城市页，都会先显示“未知”再显示当前定位

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#617]
iOS v143，Android v91
1.如果城市定位未变，进入添加城市页时，请直接显示此定位，而不是“未知”或“Location”
2.如果城市定位已变，请直接显示变化后的定位

**Comment by angel-developer** [comment]
iOS  v144 修复。

**Comment by MiaomiaoCai** [comment]
iOS V144验证已修复
