### ISSUE TITLE
pheasant，添加成功后，默认名称页面UI需调整

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#618]
Android V91
![image](https://user-images.githubusercontent.com/38175831/56956474-d677d000-6b76-11e9-9656-ab86ac4db82b.png)

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V100验证已修复
![image](https://user-images.githubusercontent.com/38175831/59168880-49a73580-8b6a-11e9-8ca1-a90eecf7381a.png)
