### ISSUE TITLE
英文，添加城市，搜索，搜不到时，iOS没有文字说明，Android的文字说明不对。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#619]
目前iOS是显示一个空列表，没有文字说明，Android是一个错误的文字说明“City not find”，请改为：
- 中文：未找到
- 繁體：未找到
- 英文：Not found

Android的现状截图如下：
![Screenshot_20190424-150642](https://user-images.githubusercontent.com/14070164/57210166-399db280-700e-11e9-8137-50248e48b6d1.png)

**Comment by Dongwei0516** [comment]
Android v92 修复。

**Comment by MiaomiaoCai** [comment]
Android V94，验证已修复
![image](https://user-images.githubusercontent.com/38175831/57594280-cea22d80-7571-11e9-9fe5-0fcd9441d231.png)

**Comment by nhoj0102** [comment]
简体和繁体系统的文字说明仍未补充

**Comment by MiaomiaoCai** [comment]
iOS V145验证已修复
