### ISSUE TITLE
英文，空气非常干燥的通知文字“Air very dry, humidity19.7%”，湿度读数前缺少空格。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#620]
![IMG_3781](https://user-images.githubusercontent.com/14070164/57210267-a1ec9400-700e-11e9-8c30-8a60dd087373.PNG)

**Comment by server-go** [comment]
已修复，请查验！

**Comment by MiaomiaoCai** [comment]
验证已修复
![image](https://user-images.githubusercontent.com/38175831/60337342-61d5dc00-99d5-11e9-9917-c32e7309f984.png)
