### ISSUE TITLE
请去掉设备详情界面的分级标准文字入口，以与城市详情界面统一。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#623]
<img width="1025" alt="Screen Shot 2019-05-06 at 3 15 17 PM" src="https://user-images.githubusercontent.com/14070164/57211160-db72ce80-7011-11e9-905e-52369eea0562.png">

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V97验证已修复

**Comment by MiaomiaoCai** [comment]
iOS V145验证已修复
![image](https://user-images.githubusercontent.com/38175831/60584193-2bc29e80-9dbf-11e9-82bb-222d6298ade2.png)
