### ISSUE TITLE
提交反馈的页面，未输入内容时，请在左上角显示一个灰色的提交按钮，输入文字后变成可点击

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#624]
Android V91
参考，iOS
![image](https://user-images.githubusercontent.com/38175831/57211676-c139f000-7013-11e9-81ce-0c90870f7e0f.png)

**Comment by Dongwei0516** [comment]
Android v95 修复。

**Comment by MiaomiaoCai** [comment]
Android V100，文案需调整，请使用提交，而不是发送
![image](https://user-images.githubusercontent.com/38175831/59168841-1c5a8780-8b6a-11e9-9b70-7406e57b2077.png)

**Comment by Dongwei0516** [comment]
Android v101 修改。

**Comment by MiaomiaoCai** [comment]
Android V103验证未修复，未输入字符时，是灰色“提交”，输入字符后是蓝色“发送”，请统一为“提交”

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64087735-ea278300-cd70-11e9-9884-3c4fcb2d0eeb.png)
![image](https://user-images.githubusercontent.com/52393989/64087745-f3185480-cd70-11e9-8bc8-d5c90d21a1a8.png)
