### ISSUE TITLE
添加WiFi版pheasant，SSID过长时，换行显示

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#629]
![image](https://user-images.githubusercontent.com/38175831/58302176-4ac32d80-7e1c-11e9-83df-ff7d6bebca39.png)
iOS V144

**Comment by angel-developer** [comment]
iOS v145 修复。

**Comment by nhoj0102** [comment]
SSID过长时，若汉字则会在第10个字节，若为字母/数字则会在第32个字节，自动截断并省略以下部分
仍需要换行。

**Comment by nhoj0102** [comment]
请在wifi名称过长时，在超过屏幕大小的部分换行显示的同时，保留最多两行内容，超过两行的部分用省略号代替，
例如：
HP-Print-64-Officejet Pro
8600 cgllc-gateway-s1_m...

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 160 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64406688-06029000-d0b5-11e9-8484-1ee703d8ee94.png)
