### ISSUE TITLE
添加WiFi版pheasant，连接WiFi的过程中没有动画效果

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#633]
![image](https://user-images.githubusercontent.com/38175831/58404717-56bb2380-8098-11e9-8654-95257beb0b6c.png)
iOS V144

**Comment by angel-developer** [comment]
iOS v145 修复。

**Comment by Dongwei0516** [comment]
Android v97 修复。

**Comment by MiaomiaoCai** [comment]
验证已修复
