### ISSUE TITLE
pheasant添加成功后，命名页面UI需调整

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#635]
V95
![image](https://user-images.githubusercontent.com/38175831/58464079-a0bf0a80-8167-11e9-8550-daaca7b69687.png)

**Comment by Dongwei0516** [comment]
Android v100 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/59168660-41022f80-8b69-11e9-8388-7e5f57d78116.png)
验证已修复
