### ISSUE TITLE
共享设备到微信好友，显示方式请参考iOS

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#636]
Android V144
![image](https://user-images.githubusercontent.com/38175831/58550700-ef8ca300-8240-11e9-9be4-94560cdfca1b.png)
![image](https://user-images.githubusercontent.com/38175831/58550730-03380980-8241-11e9-8f5c-18028406caf6.png)

**Comment by Dongwei0516** [comment]
Android v97 修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/58793306-6bfbf900-8628-11e9-8d26-171a9a2b73b5.png)
Android V98验证已修复
