### ISSUE TITLE
设备城市编辑列表排序后，其他设备也带有来自“XX”的字符

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#640]
Android V100
前提
1.已有两台pheasant
操作步骤
1.接受了一台共享pheasant
2.进入设备编辑列表-对设备排序-返回首页
3.另外两台设备都带有来自“XX”的字符

**Comment by Dongwei0516** [comment]
Android v101 修复。

**Comment by MiaomiaoCai** [comment]
103验证已修复
