### ISSUE TITLE
花粉较高时，城市卡片、详情页，行动建议有误

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#641]
Android V100
1.首页卡片，行动建议最后一行应是“佩戴口罩”
2.详情页，花粉过敏人士的字符，应使用灰色
![image](https://user-images.githubusercontent.com/38175831/59177100-96e8ce80-8b8d-11e9-8261-0beadedf9efd.png)
![image](https://user-images.githubusercontent.com/38175831/59177110-a10acd00-8b8d-11e9-851a-fd285703e99d.png)

**Comment by Dongwei0516** [comment]
Android v101 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证已修复
![image](https://user-images.githubusercontent.com/52393989/64092387-2bc32880-cd87-11e9-926b-428e45451599.png)
