### ISSUE TITLE
自定义的设备名称被清空后，没有显示默认名称

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#645]
Android V102
![image](https://user-images.githubusercontent.com/38175831/59321218-c91c3c80-8d03-11e9-811f-8ca02d9aa745.png)

**Comment by Dongwei0516** [comment]
Android v103 修复。

**Comment by nhoj0102** [comment]
自定义名称清空后，未显示默认名称
[![Screenshot_2019-06-26-15-19-35-712_com cleargrass](https://user-images.githubusercontent.com/51428604/60159568-56ea3400-97a8-11e9-8024-8677b56ba4da.png)
](url)
默认名称请使用“Temp & RH Monitor”
<img width="375" alt="企业微信截图_15615335583336" src="https://user-images.githubusercontent.com/51428604/60159781-ceb85e80-97a8-11e9-85a8-e21c55eacf85.png">

**Comment by Dongwei0516** [comment]
Android v104 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复。
![image](https://user-images.githubusercontent.com/52393989/63835578-4faef480-c9aa-11e9-8c62-dfbfaad1a89d.png)
![image](https://user-images.githubusercontent.com/52393989/63835594-589fc600-c9aa-11e9-9ee5-426a4dac7adc.png)
