### ISSUE TITLE
读数解释页，最后一行文字与底部需留出适当的空行，且超过一屏时需有滑动效果

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#649]
Android V102
![image](https://user-images.githubusercontent.com/38175831/59421781-c142c200-8e01-11e9-81a4-f4362fbe26ba.png)

**Comment by Dongwei0516** [comment]
Android v103 修复。

**Comment by nhoj0102** [comment]
已修复
