### ISSUE TITLE
设备管理中的MAC地址格式需规范，即XX:XX:XX（大写字母+英文冒号）

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#650]
如题。

**Comment by angel-developer** [comment]
iOS v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 验证修复
![IMG_0047](https://user-images.githubusercontent.com/52393989/61102270-c302b280-a49f-11e9-8302-dfe2beb0f234.PNG)
