### ISSUE TITLE
“数据上报和通知”界面，英文状态，界面上的问题。详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#652]
![IMG_4008](https://user-images.githubusercontent.com/14070164/60080971-7874fc80-9763-11e9-96ee-bd252b14e07d.png)

**Comment by dubinbeta** [comment]
下图是个过长的大标题，可参考：
![WechatIMG53](https://user-images.githubusercontent.com/14070164/60114988-83518080-97a7-11e9-862f-490fa228f7d2.jpeg)

**Comment by angel-developer** [comment]
v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 验证未修复
![image](https://user-images.githubusercontent.com/52393989/61101248-a06e9a80-a49b-11e9-8a31-39757b6c06da.png)

**Comment by angel-developer** [comment]
内测版 iOS v170 修复。

**Comment by jiaruirui323** [comment]
内测版 iOS v170 验证未修复
![image](https://user-images.githubusercontent.com/52393989/62349808-6d1baa80-b533-11e9-9f45-fd9c621b7755.png)

**Comment by jiaruirui323** [comment]
内测版 iOS v170 验证未修复
![image](https://user-images.githubusercontent.com/52393989/62349808-6d1baa80-b533-11e9-9f45-fd9c621b7755.png)

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/64097740-a005c800-cd97-11e9-8513-bb752d9e53c5.png)

**Comment by jiaruirui323** [comment]
iOS 158 验证修复
![image](https://user-images.githubusercontent.com/52393989/64097930-173b5c00-cd98-11e9-8136-58d1537f8be6.png)
