### ISSUE TITLE
“数据上报和通知”界面，英文状态，选择时间间隔和数据颗粒度的滚轴的问题，以及界面上的单位用词和单复数的问题。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#654]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/14070164/60162601-762aa500-982c-11e9-8886-f129f357da26.png">

**Comment by angel-developer** [comment]
iOS v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 验证修复
![IMG_0042](https://user-images.githubusercontent.com/52393989/61100721-b5e2c500-a499-11e9-9d35-5e5ce49adc2c.PNG)
![IMG_0041](https://user-images.githubusercontent.com/52393989/61100728-bc713c80-a499-11e9-97ca-eebcc670e445.PNG)

**Comment by Dongwei0516** [comment]
Android v112 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
![image](https://user-images.githubusercontent.com/52393989/63837700-930b6200-c9ae-11e9-863b-5073df4f38f1.png)
