### ISSUE TITLE
触发通知的条件列表界面的用词和换行问题，详见评论附图。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#655]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/14070164/60162736-b7bb5000-982c-11e9-8781-2f78cbea70b0.png">

**Comment by dubinbeta** [comment]
这里也一样：

<img width="467" alt="Screen Shot 2019-06-26 at 4 11 21 PM" src="https://user-images.githubusercontent.com/14070164/60162939-24cee580-982d-11e9-8359-ce4a763a35cc.png">

**Comment by angel-developer** [comment]
v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 中文繁体 “生效时段” 显示不正确
![image](https://user-images.githubusercontent.com/52393989/61100517-158ca080-a499-11e9-82c6-b39675a5364e.png)

**Comment by angel-developer** [comment]
内测版 v170 修复。

**Comment by jiaruirui323** [comment]
内测版 v170 验证修复
![IMG_0057](https://user-images.githubusercontent.com/52393989/62349112-583e1780-b531-11e9-94fd-95c98d93b9b5.PNG)
