### ISSUE TITLE
创建或修改触发上报的条件的界面，用词问题。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#656]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/14070164/60162965-34e6c500-982d-11e9-9f1f-05431a9cb9c0.png">

**Comment by angel-developer** [comment]
v146 修复。

**Comment by jiaruirui323** [comment]
iOS 147 繁体 “生效时段” 显示不正确
![image](https://user-images.githubusercontent.com/52393989/61100323-63ed6f80-a498-11e9-91fe-d8de847babdc.png)

**Comment by angel-developer** [comment]
内测版 v170 修复。

**Comment by jiaruirui323** [comment]
iOS v149验证修复
![IMG_0058](https://user-images.githubusercontent.com/52393989/62349363-1cf01880-b532-11e9-98c7-46a4080845cb.PNG)
![IMG_0059](https://user-images.githubusercontent.com/52393989/62349372-237e9000-b532-11e9-847e-4bc333a88ada.PNG)
![IMG_0057](https://user-images.githubusercontent.com/52393989/62349390-31ccac00-b532-11e9-837c-4545984d67f5.PNG)
