### ISSUE TITLE
和亲友共享设备，取消共享返回设备管理页，导致数据上报和通知、导出历史数据不可点击，发生闪退

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#659]
安卓APP  103
1、成功添加了pheasant，进入设备详情页
2、进入设备管理
3、选择和亲友共享设备，取消共享返回设备管理页
4、操作点击数据上报和通知 或 导出历史数据
实际结果：发生闪退
![Screenshot_2019-07-03-10-29-01-616_com cleargrass](https://user-images.githubusercontent.com/52393989/60560052-fdbe6980-9d80-11e9-9780-c45dbc7b4634.png)
![Screenshot_2019-07-03-10-28-22-451_com miui bugre(1)](https://user-images.githubusercontent.com/52393989/60560057-ff882d00-9d80-11e9-8995-c0c92f71213f.png)

**Comment by jiaruirui323** [comment]
选择和亲友共享设备，取消共享返回设备管理页，返回设备详情页
实际结果：设备详情页设备管理按钮和分享按钮不能点击

**Comment by Dongwei0516** [comment]
Android v120 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复
