### ISSUE TITLE
PM2.5名词解释 字体不一致多字符

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#660]
安卓OPPO A7x  101
已添加设备空气检测仪，进入设备详情页，点击PM2.5进入名词解释页
![NXZZ(PY~E`IFB4SIYR9}BWO](https://user-images.githubusercontent.com/52393989/60562381-eb94f900-9d89-11e9-8e28-371b6be822f6.png)

**Comment by Dongwei0516** [comment]
Android v112 修复。

**Comment by jiaruirui323** [comment]
Android v120  验证修复。
![image](https://user-images.githubusercontent.com/52393989/63834954-0d38e800-c9a9-11e9-9647-2800c5bdd3e1.png)
