### ISSUE TITLE
iPhone 6，三个卡片占满屏幕时，加号不可用

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#662]
iOS V145
![image](https://user-images.githubusercontent.com/38175831/60645503-6c77f180-9e6b-11e9-87c8-47a383ea2844.png)

**Comment by angel-developer** [comment]
v146 修复。

**Comment by jiaruirui323** [comment]
![IMG_0036](https://user-images.githubusercontent.com/52393989/61098727-8c726b00-a492-11e9-9dd3-a8f1ef55a382.PNG)
147 修复
