### ISSUE TITLE
城市详情页，AQL预报7天的数据展示，左右留白不一致

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#666]
![image](https://user-images.githubusercontent.com/52393989/61027724-75c40980-a3e9-11e9-9c27-87e0c53880ac.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64167218-5e4e4d80-ce7b-11e9-9e63-acb0ddcb0c48.png)
