### ISSUE TITLE
Snow设备详情页PM2.5，24小时数据，数据条颜色和文字颜色不一致

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#668]
![X{Q6WCF09TAFB0G5FDX7J$0](https://user-images.githubusercontent.com/52393989/61028299-f20b1c80-a3ea-11e9-822f-2889e4b78ec6.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
