### ISSUE TITLE
iOS：设置-已登录，已登录的微信 ID 文字显示不全：图中字母“y”的下部分没有显示出来

### ISSUE THREAD

**Issue by Jackacey** [ClearGrass/Air-App-Issues#67]
如题。
![img_0288](https://user-images.githubusercontent.com/37140201/40594389-83fa89a4-6261-11e8-8fd1-bfbcccb428a1.PNG)

**Comment by GuiYongZhao** [comment]
“y”在哪？我没有看到。

**Comment by Jackacey** [comment]
抱歉，之前上传错图片，已更新。请看原评论中的新图片。

**Comment by GuiYongZhao** [comment]
懂了。
