### ISSUE TITLE
城市详情页，天气信息图标需调整适配

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#671]
湿度、风级、降雨率图标偏小，需调大，限行图标需加斜杠
![image](https://user-images.githubusercontent.com/38175831/61365219-ed96a600-a8b9-11e9-896a-eb3e25d6c18c.png)

**Comment by Dongwei0516** [comment]
Android v112 修复。

**Comment by jiaruirui323** [comment]
Android v120  验证未修复。
![image](https://user-images.githubusercontent.com/52393989/63838440-f0ec7980-c9af-11e9-8421-59f055c050ab.png)
