### ISSUE TITLE
设定温度单位为℉后，城市的温度范围，温湿度详情页仍使用℃作为单位

### ISSUE THREAD

**Issue by nhoj0102** [ClearGrass/Air-App-Issues#673]
如图，在下方的温度数据一直为摄氏度，不随设置变化而改变
![1d5953d0-839e-4cc1-9e0a-389dd99391d8](https://user-images.githubusercontent.com/51428604/61507306-12624a80-a99a-11e9-9aed-8ad2954325b4.jpg)

**Comment by MiaomiaoCai** [comment]
Android V109

**Comment by Dongwei0516** [comment]
Android v112 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复。
![image](https://user-images.githubusercontent.com/52393989/64098324-2c64ba80-cd99-11e9-8891-d8fb053c7608.png)
