### ISSUE TITLE
温湿度详情，“相对湿度 %”文字展示不全顶部缺失一部分，“温度℃”文字数字展示不全大部分缺失

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#676]
![image](https://user-images.githubusercontent.com/52393989/61783320-2abee300-ae3a-11e9-833e-71565ff814ba.png)

**Comment by Dongwei0516** [comment]
Android v112修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复。
![image](https://user-images.githubusercontent.com/52393989/64096707-e86fb680-cd94-11e9-9082-371e6d260184.png)
