### ISSUE TITLE
Pheasant数据上报间隔，单位单复数错误。

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#677]
![image](https://user-images.githubusercontent.com/52393989/62018998-8fd65800-b1ef-11e9-8fc8-27670eff3bf4.png)
![image](https://user-images.githubusercontent.com/52393989/62019127-0bd0a000-b1f0-11e9-9ca5-9cee00c7830b.png)

**Comment by Dongwei0516** [comment]
Android v112 修复。

**Comment by jiaruirui323** [comment]
Android v120 验证修复。
![image](https://user-images.githubusercontent.com/52393989/63833194-04deae00-c9a5-11e9-8ddb-13c8e1c1298d.png)
