### ISSUE TITLE
1 hour、 1 minute，都统一为小写。

### ISSUE THREAD

**Issue by jiaruirui323** [ClearGrass/Air-App-Issues#678]
![image](https://user-images.githubusercontent.com/52393989/62019538-ee9cd100-b1f1-11e9-83ef-f2658dd748a4.png)
![企业微信截图_15643702603291(1)](https://user-images.githubusercontent.com/52393989/62019668-7edb1600-b1f2-11e9-9384-dfe3c3db8111.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64166013-c8192800-ce78-11e9-84c7-692749e18676.png)
