### ISSUE TITLE
网络较差时，导出历史数据提交邮箱后，缺少动态加载动画

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#679]
![image](https://user-images.githubusercontent.com/38175831/62098447-f6757780-b2bc-11e9-8863-63ab2bb2ee03.png)

**Comment by GuiYongZhao** [comment]
加载动画见附图，此时邮箱地址不可编辑。
<img width="300" alt="image" src="https://user-images.githubusercontent.com/37681560/62264629-4be38d00-b453-11e9-9406-9cfaac5d8845.jpg">

**Comment by GuiYongZhao** [comment]
此需求已移至TAPD。
