### ISSUE TITLE
蓝牙设备未连接时，电池图标与蓝牙i图标重叠

### ISSUE THREAD

**Issue by MiaomiaoCai** [ClearGrass/Air-App-Issues#681]
![image](https://user-images.githubusercontent.com/38175831/62273318-d639ea00-b46f-11e9-9c1e-063327ca9d33.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64320675-a0999b00-cff1-11e9-9610-702490599f3f.png)
