### ISSUE TITLE
创建触发上报的条件的时候，选择数值的滚轴界面，请和上一级（选择数值类型的）界面合并。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#685]
![IMG_4241](https://user-images.githubusercontent.com/14070164/63591287-e6616700-c5e0-11e9-88ea-4b9a212fdb0c.png)

![IMG_4242](https://user-images.githubusercontent.com/14070164/63591742-3856bc80-c5e2-11e9-8c9d-6a34d77785c1.png)

**Comment by angel-developer** [comment]
iOS v1.1.6 159 线条和返回按钮已更改.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 线条和返回按钮 验证已修改
![image](https://user-images.githubusercontent.com/52393989/64230876-9bb8e680-cf20-11e9-94a1-49526295a57e.png)
