### ISSUE TITLE
创建或修改触发通知的条件的界面的问题。详见评论

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#686]
1.
![IMG_4242](https://user-images.githubusercontent.com/14070164/63592710-d9467700-c5e4-11e9-92b2-ac92da69a14b.png)

2. 注意：修改后，界面的飞入动画，需要改为从底部飞入。
![Pasted_Image_2019_8_23__8_32_PM](https://user-images.githubusercontent.com/14070164/63592952-68538f00-c5e5-11e9-8585-502242ac7acf.png)

3.
![IMG_4243](https://user-images.githubusercontent.com/14070164/63592720-e2374880-c5e4-11e9-9d59-c8d96428bc1a.png)

**Comment by angel-developer** [comment]
iOS  v1.1.6 159 修复。

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64162521-1119ae00-ce72-11e9-8984-339bd7aed0d7.png)

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159  设备添加添加条件页，应该用返回不应该用“×”
![image](https://user-images.githubusercontent.com/52393989/64164663-2b558b00-ce76-11e9-9921-f8e1c84d0c1a.png)
