### ISSUE TITLE
修改设备名称的界面，左上角应使用“x”按钮，表示取消。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#687]
如题。
![IMG_4247](https://user-images.githubusercontent.com/14070164/63593047-acdf2a80-c5e5-11e9-8845-91fa7ed36339.png)

**Comment by dubinbeta** [comment]
注意：界面的飞入动画，需要改为从底部飞入。

**Comment by angel-developer** [comment]
iOS v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证修复
![image](https://user-images.githubusercontent.com/52393989/64160765-1aede200-ce6f-11e9-8d2c-3113e61d2fa8.png)
