### ISSUE TITLE
“联系我们”的界面，左上角应使用“x”，表示关闭或取消。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#688]
如题。相应地，界面的飞入动画应该是从底部往上，关闭时相反。
![IMG_4256](https://user-images.githubusercontent.com/14070164/63868078-8441a100-c9e8-11e9-8780-f5bc1ba4c244.png)
![IMG_4257](https://user-images.githubusercontent.com/14070164/63868081-860b6480-c9e8-11e9-8615-9dbd17eba568.png)

**Comment by angel-developer** [comment]
iOS  v1.1.6 159 Fixed.

**Comment by jiaruirui323** [comment]
iOS v1.1.6 159 验证已修复。
![image](https://user-images.githubusercontent.com/52393989/64160495-9dc26d00-ce6e-11e9-99ae-ee412a2a5e97.png)
