### ISSUE TITLE
在新的icon设计完成后，应该重新设计app的启动画面，目前的大面积蓝色并不合适（app里面没有应用大面积蓝色）。另外，启动画面上不要出现中文，因为启动画面无法分语言。

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#71]
如题。

**Comment by dubiao** [comment]
@dubinbeta 启动画面可以区分语言。

**Comment by dubiao** [comment]
准确地说，启动画面可以区分系统语言，如果在app内单独设置过app的语言则不能区分。

> 以前有设置语言的功能，后来被某个狂妄的程序员砍了。

**Comment by dubinbeta** [comment]
砍掉设置语言的功能，也是得到我支持的，app语言和系统语言保持一致是常见的做法。

哪怕启动画面可以区分语言，也不要在启动画面上显示文字了（也就不需要做区分了），因为启动画面有个洋气的图就够了。
