### ISSUE TITLE
添加设备页的描述步骤，目前并没有针对小屏手机优化，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#75]
![image](https://user-images.githubusercontent.com/37681560/40758528-5b8925c8-64c0-11e8-9947-326fd24ef5fe.png)

**Comment by dubinbeta** [comment]
这个界面上的文字显示区域的宽度占比过小，在大屏幕上也换行过早：
![img_1345](https://user-images.githubusercontent.com/14070164/40759626-7d83f22a-64c5-11e8-9d33-7318904bca4e.png)

下面这是最新的设计效果图：
![1](https://user-images.githubusercontent.com/14070164/40759656-a59c55b8-64c5-11e8-8af3-5862a75a12c8.png)

**Comment by dubinbeta** [comment]
另外，“现在购买”下方的下划线糊在文字上了。

**Comment by dubiao** [comment]
不过，过早换行这种问题无法肯定绝对地改正。
间距是按设计走的，文字的换行方式由系统决定。可以做一点修正。再要完美就只能分屏幕大小出设计了。

**Comment by dubinbeta** [comment]
这几个问题不至于需要区分大小屏幕分别做设计，完全可以用一套逻辑对付所有机型。

**Comment by GuiYongZhao** [comment]
当文字显示不下时，换行。
并且，保持整段文字与左边的数字水平居中就可以了。

**Comment by angel-developer** [comment]
文字换行我可以在“设置”后面加个“\n” 换行符 然后再看看在小屏 iPhoneSE效果 稍微调动一下

**Comment by dubinbeta** [comment]
@angel-developer ，并不是要在指定的文字后面换行。

@GayoZhao 指出的问题是在小屏手机（iPhone SE）上文字未被全部显示出来。

我指出的问题是，用于显示文字的宽度太小（即“换行过早”，这个问题可能也让小屏手机更难在2行内显示完现有文字了）。

看不明白的话，二位找我当面聊一下。

**Comment by GuiYongZhao** [comment]
懂了，建议 @beibeixiao666 加宽整体文字的显示宽度。
