### ISSUE TITLE
iOS 1.0.0(20)版本，添加设备后，自动添加了一个城市卡片，登录微信后，该城市卡片自动消失，过了一段时间（一晚上），该卡片又回来了

### ISSUE THREAD

**Issue by Jackacey** [ClearGrass/Air-App-Issues#79]
这里我有两个疑问：
1. 添加设备后，自动添加（设备所在）城市卡片，这个卡片往往会跟“当前定位卡片”的信息重合，因为用户添加设备时，往往跟设备是在一起的。自动添加容易造成用户疑惑。（可能有少数用户的位置和设备离得较远，他们可以自己添加城市卡片。）
2. 似乎“登录微信”的操作会影响首页卡片的显示，也可能是首页卡片显示不稳定。未进行多次验证，不确定跟登录操作有关。

![1-](https://user-images.githubusercontent.com/37140201/40819219-209272e4-658d-11e8-9952-a059462dd2cf.PNG)
![2-](https://user-images.githubusercontent.com/37140201/40819220-213618ae-658d-11e8-8eb9-b19da9e3ed22.PNG)

**Comment by dubinbeta** [comment]
@Jackacey 说了2个问题：

问题1：的确存在这个问题。我们修改一下需求，把随设备添加城市卡片的功能去掉，@GayoZhao 。
问题2：是个bug。

**Comment by GuiYongZhao** [comment]
好的，同意去掉。
