### ISSUE TITLE
申请定位权限的需求

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#89]
##  **申请定位权限的时机：**
* 从未申请定位权限，添加完第一个设备或城市后，在该城市或设备的卡片上方自动出现“显示当前城市空气质量”提示卡片，点击提示卡片，弹出定位权限请求提示框。如用户允许，则提示卡片变为当前城市空气质量卡片；如用户拒绝，则提示卡片消失，但是，在“管理城市和设备”的界面，仍然可以看到“显示当前城市空气质量”条目，只是状态为关。
* 从未申请定位权限，添加“城市空气质量”（即进入选择城市的界面）时，弹出定位权限请求提示框。如用户同意，则选择城市的界面显示当前定位城市名字，并带有定位标识；如用户拒绝，则选择城市的界面上显示一个文字为“当前城市”的item，并带有定位标识。   
* 从未申请定位权限，在“管理城市和设备”的界面，手动开启“当前城市”开关。
  * “当前城市”开关为关时，此开关的文字是“当前城市”，并带有定位标识。
  * “当前城市”开关为开时，此开关的文字是当前定位城市名（例，北京市朝阳区），并带有定位标识。

## **如申请定位权限被用户拒绝，之后提示用户去系统设置中手动给予权限的时机：**
* 当用户在管理城市或设备的界面点击开关启用“显示当前城市空气质量”时。（现在这一条的实现有bug：已获得定位权限后，关闭“显示当前城市空气质量”后再次开启，也会提示前往设置界面给予定位权限。这是错的，因为定位权限已经有了，这时的开关是app自身控制的，不需要再去索取系统权限，直接重新开始显示即可。）
* 当用户在“添加城市 - 选择城市”界面点击“当前城市”时。

## **登录/退出登录的影响：**
登录/退出登录不影响“显示当前城市空气质量”的状态。如未重装app，用户主动登出，则“显示当前城市空气质量”的状态不变，保持登出前的状态；如用户重装app，则“显示当前城市空气质量”的状态应重建，和用户上一次登录时的状态无关（也和用户重装后是否重新登录无关），即这个状态不同步到服务器上去，因为同步了也没用，重装app无论如何都需要重新获取权限。

**Comment by dubiao** [comment]
- 显示提示卡片的时机是
    - 从未申请定位权限，并且列表里有城市或设备时

- 弹出定位权限请求提示框的时机是：
  - 点击提示卡片，弹出定位权限请求提示框。
    - 如用户允许，则提示卡片变为当前城市空气质量卡片；
    - 如用户拒绝，则提示卡片消失
  - 从未申请定位权限，第一次 添加“城市空气质量”时
    - 如用户允许，城市列表上头第一个显示为 当前城市的名字
    - 如用户拒绝，城市列表上头第一个显示为 “当前城市”
  - 从未申请定位权限，从设置里点击开关
    - 如用户允许，则显示前城市空气质量卡片，开关显示为开；
    - 如用户拒绝，开关显示为关。
- 提示用户跳转到系统设置的时机：
    - 用户以前拒绝了权限，从设置里点击开启开关时
    - 用户以前拒绝了权限，在添加城市时点击“定位城市”时

**Comment by MiaomiaoCai** [comment]
iOS 97，Android 61验证已修复
