### ISSUE TITLE
首页，行动建议的界面优化，附图

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#95]
行动建议的文字，有可能是一行、两行、三行，甚至是没有文字。

**所以此卡片的高度，需要随着行动建议文字的行数多少，进行调整。**

（目前设置的高度是固定地显示两行，容易出现问题，比如下图，只有一行文字，上边的留白太大了）

<img width="375" alt="image" src="https://user-images.githubusercontent.com/37681560/41091899-3bf70d50-6a7a-11e8-94a7-8d73a23f20b3.png">

**Comment by dubinbeta** [comment]
这是不言自明的，请工程师们注意。
