### ISSUE TITLE
Android, 当有新版本时，应在主界面右上角的“设置”处显示小红点

### ISSUE THREAD

**Issue by dubinbeta** [ClearGrass/Air-App-Issues#97]
如题。

**Comment by dubinbeta** [comment]
有新版时，应有弹窗。

**Comment by Dongwei0516** [comment]
Android v77 已修复。

**Comment by MiaomiaoCai** [comment]
![image](https://user-images.githubusercontent.com/38175831/54405902-024c0d00-4713-11e9-9d97-a6d28de3bafb.png)
验证已修复
