### ISSUE TITLE
邮件共享，输入邮箱地址的交互

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#98]
![image](https://user-images.githubusercontent.com/37681560/41329327-a61cb6e2-6eff-11e8-8d50-39cb13941031.png)

**Comment by dubiao** [comment]
匹配联系人要申请联系人读取的权限。望知。

**Comment by dubinbeta** [comment]
@GayoZhao @dubiao @angel-developer @Dongwei0516 ，那就去掉匹配联系人功能。
