### ISSUE TITLE
自定义设备名称（包括“修改设备名称”），交互优化

### ISSUE THREAD

**Issue by GuiYongZhao** [ClearGrass/Air-App-Issues#99]
![image](https://user-images.githubusercontent.com/37681560/41333560-d6c7e1b2-6f14-11e8-84de-7f00397a4115.png)

**Comment by dubinbeta** [comment]
“完成”应该在右上角。

**Comment by MiaomiaoCai** [comment]
84验证已修复

**Comment by Dongwei0516** [comment]
Android v77 修复。

**Comment by MiaomiaoCai** [comment]
Android V77，验证右上角已添加“完成”按钮
![image](https://user-images.githubusercontent.com/38175831/54348862-f285e780-4684-11e9-86f0-35d91b1c4d55.png)
